### PR TITLE
PULL_REQUEST_TEMPLATE.md specifically for gitlab-plugin for quality PR's 

### LINKED ISSUE #1625: Add pull_request_template.md for standardized format to submit changes
### What feature do you want to see added?

A standard pull request template so the contributors can describe their changes and it will be also helpful for maintainers

### Upstream changes

_No response_

### Are you interested in contributing this feature?

Yes

### PR DESCRIPTION
**Pull request by AniketNS**
## PULL_REQUEST_TEMPLATE.md specifically for gitlab-plugin for quality PR's 

Fixes #1625 
Created a PULL_REQUEST_TEMPLATE.md specifically for gitlab-plugin which gives better way to describe the pull request than the default one https://github.com/jenkinsci/.github/blob/master/.github/pull_request_template.md 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/jenkinsci/gitlab-plugin/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that verify my changes
- [ ] Unit tests pass locally with my changes
- [ ] I have added documentation as necessary
- [x] No Javadoc warnings were introduced with my changes
- [x] No spotbugs warnings were introduced with my changes
- [x] I have interactively tested my changes

## Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

- [ ] Infrastructure change (non-breaking change which updates dependencies or improves infrastructure)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by krisstern — CHANGES_REQUESTED** [review]
For this type of issue it would be better for the repo maintainers to decide on the contents for the template. I have issues with how the wordings are used in your suggested template.

**Comment by AniketNS** [comment]
> For this type of issue it would be better for the repo maintainers to decide on the contents for the template. I have issues with how the wordings are used in your suggested template.

I've referenced this template from https://github.com/jenkinsci/git-client-plugin/blob/master/.github/pull_request_template.md

**Comment by krisstern** [comment]
My opinion is that I am not in favor of making this change, and would much prefer the current template used.

**Comment by krisstern** [comment]
> > For this type of issue it would be better for the repo maintainers to decide on the contents for the template. I have issues with how the wordings are used in your suggested template.
> 
> I've referenced this template from https://github.com/jenkinsci/git-client-plugin/blob/master/.github/pull_request_template.md

I think that is used for the `Git` plugin only?

**Comment by AniketNS** [comment]
> > > For this type of issue it would be better for the repo maintainers to decide on the contents for the template. I have issues with how the wordings are used in your suggested template.
> > 
> > 
> > I've referenced this template from https://github.com/jenkinsci/git-client-plugin/blob/master/.github/pull_request_template.md
> 
> I think that is used for the `Git` plugin only?

Ohh Ok @krisstern

**Comment by AniketNS** [comment]
Should I close this PR?

**Comment by krisstern** [comment]
Sure

**Pull request closed without merging**
