### PR TITLE
Add the user_username field to the push hook, cause data and env

### PR DESCRIPTION
**Pull request by bbreijer**
The `user_name` field in the GitLab webhook is a field which can be edited by the Gitlab user (in Gitlab it maps to the Full name), while the user_username can only be edited by a Gitlab-admin and therefore provides a much more traceable source.
In this pull request, the field is edited to the CauseData and mapped to the environment variable `gitlabUserUsername`.
A simple but (imho) sufficient test is added.

Please let me know if you have any comments or suggestions for improvements.

### CODE REVIEW

**Comment by markjacksonfishing** [comment]
@bbreijer Is there an associated Github issue with this PR? What about a Jenkins jira? If so, can you link them? If not, can you open them and note this PR?
Thank you for that.
I am coming onboard as a maintainer and link to make sure we keep as much details across the Jenkins spectrum as well.
Thanks again :-)

**Comment by bbreijer** [comment]
#973 @markyjackson-taulia I created an Issue for the feature. Let me know if you need anything else!

**Comment by markjacksonfishing** [comment]
Thank you @bbreijer

**Comment by markjacksonfishing** [comment]
Going to need to fix the ci build

**Comment by bbreijer** [comment]
I looked at the failure, but it seems related to workspace cleanup, not the code (`
Unable to delete 'C:\Jenkins\workspace\Plugins_gitlab-plugin_PR-969'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.`).
Is there an easy way to retrigger a ci build?

**Comment by bbreijer** [comment]
@markyjackson-taulia After posting the previous reply, i noticed that the dependencies on master where broken. So i fixes these, the tests and code in this PR.
I don't have the ability to check the correct function of the plugin in a semi-live situation, could you check this before merging?

**Comment by markjacksonfishing** [comment]
Thank you @bbreijer

**Comment by markjacksonfishing** [comment]
@bbreijer I will get a release out tonight or tomorrow

**Pull request merged**
