### PR TITLE
Have OpenMergeRequestPushHookTriggerHandler accept pipeline/workflow …

### LINKED ISSUE #515: Trigger for Open Merge Requests non-functional in pipeline jobs
### Context
- **Gitlab plugin version**: 1.4.6
- **Gitlab version**: 8.16.1
- **Jenkins version**: 2.45
- **Job type**: Pipeline

### Problem Description

There is a "bug" in the OpenMergeRequestPushHookTriggerHandler. The handler assumes that the Job is an instance of the AbstractProject class. 
```java
            if (job instanceof AbstractProject<?, ?>) {
                AbstractProject<?, ?> project = (AbstractProject<?, ?>) job;
```

However, apparently (I'm not an expert in Jenkins) pipeline/workflow jobs do not inherit from that class. Instead workflow jobs re-implement the interface related to triggers (ParameterizedJobMixIn.ParameterizedJob).

Since there's no reason to rely on AbstractProject, I refactored this to use the common interface method:
```java
            if (job instanceof ParameterizedJobMixIn.ParameterizedJob) {
                ParameterizedJob project = (ParameterizedJobMixIn.ParameterizedJob) job;
                GitLabConnectionProperty property = job.getProperty(GitLabConnectionProperty.class);
                for (Trigger t : project.getTriggers().values()) {
                	if (t instanceof GitLabPushTrigger) {
                		final GitLabPushTrigger trigger = (GitLabPushTrigger) t;
```

I'm going to supply a merge request with the fix.

### PR DESCRIPTION
**Pull request by czoellin**
Fixes #515, #491

### CODE REVIEW

**Comment by omehegan** [comment]
@czoellin thanks! I guess I don't understand what, if anything, is broken without this fix. Can you elaborate?

**Comment by czoellin** [comment]
Without this fix, the trigger for pushes to the destination branch of open merge requests do not work in pipeline scripts. The reasons for this is that pipeline jobs do not implement the AbstractProject class, which the current implementation of the trigger assumes.

The fix changes that to a more general interface ParameterizedJobMixIn.ParameterizedJob, which both AbstractProject and pipeline jobs implement.

**Comment by omehegan** [comment]
@czoellin thanks! Do you think this is also the cause of this issue? https://github.com/jenkinsci/gitlab-plugin/issues/491

**Comment by czoellin** [comment]
Yes, absolutely. Sorry I missed that. This is a perfect duplicate of #491.

**Comment by vills** [comment]
@omehegan how about to release this?

**Comment by omehegan** [comment]
@mreichel or @colourmeamused can you review this? I think we should try to get a release out soon with some of these PRs :)

**Review by mreichel — APPROVED** [review]
Looks good to me!

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.

**Pull request merged**
