### PR TITLE
Adding gitlabMergeRequestTargetProjectId variable

### PR DESCRIPTION
**Pull request by tomasbjerre**
The project ID is needed when using the GitLab rest API to get information about the merge request.

### CODE REVIEW

**Comment by tomasbjerre** [comment]
@omehegan Tell me if there is anything unclear here.

I really need this in order to use https://github.com/jenkinsci/violation-comments-to-gitlab-plugin

**Comment by omehegan** [comment]
@tomasbjerre thanks! This looks pretty straightforward. I normally merge small PRs like this in groups and do a release. I will try to do one in the next few days.

**Comment by drndos** [comment]
You forgot to edit MergeRequestHookTriggerHandlerImpl
and add `.withMergeRequestTargetProjectId(hook.getObjectAttributes().getTargetProjectId())`
after `.withMergeRequestIid(hook.getObjectAttributes().getIid())`

**Comment by tomasbjerre** [comment]
Fixed

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.

**Pull request merged**
