### PR TITLE
Update jenkins.version to 2.7.1 and test-harness to 2.4.0

### PR DESCRIPTION
**Pull request by deepy**
Update `jenkins.version` and `jenkins-test-harness.version` with the goal of enabling testing of pipeline steps.

### CODE REVIEW

**Review by Wadeck — CHANGES_REQUESTED** [review]
There is a test failure, I imagine due to the change of Jetty implementation.
Otherwise always nice to see an update of plugin 👍

**Comment by deepy** [comment]
@Wadeck help would be greatly appreciated as I currently got limited time and had to take a pause from this after failing to figure out why it fails :-)

**Comment by omehegan** [comment]
@deepy any chance you will have time to look at this soon? Did you need help from @Wadeck?

**Comment by Wadeck** [comment]
@omehegan @deepy I have investigated a bit. The root cause is the incompatibility between jenkins-test-harness and parent pom versions. Parent pom includes as dependency servlet-api:2.4 but in jenkins-test-harness, we expect 3.1+.

Quick advice: upgrade parent pom + jenkins-test-harness to latest version, that will solve *that* problem but perhaps add new ones. After that the plugin will be more up-to-date.

**Comment by deepy** [comment]
Upgrading parent pom + jth to latest version resulted in some dependency juggling, will pursue that a bit further

**Comment by omehegan** [comment]
@deepy do you think you will be able to work on this anytime soon?

**Pull request closed without merging**
