### PR TITLE
WIP: Export MR labels as build variable

### PR DESCRIPTION
**Pull request by jakub-bochenski**
This is the most basic approach, joining the labels with a space into a single env

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
Unfortunately it seems that label are always null.
I've filled a support request with gitlab since label filtering is broken now

**Comment by omehegan** [comment]
@jakub-bochenski what is the status of this PR?

**Comment by jakub-bochenski** [comment]
@omehegan  still waiting for #647 to be fixed

**Comment by omehegan** [comment]
@jakub-bochenski #647 was fixed in v1.5.5 of the plugin, can we move this PR forward?

**Comment by jakub-bochenski** [comment]
Will try

**Comment by omehegan** [comment]
Still hoping we can release this soon!

**Comment by jakub-bochenski** [comment]
Resolved conflicts, lets see if tests pass..

**Comment by omehegan** [comment]
This does not even build. Reopen if you can get this working and want to merge it.

**Pull request closed without merging**
