### PR TITLE
Automatically sync the project branch every day

### PR DESCRIPTION
**Pull request by basil**
This will create a pull request once a day (at midnight UTC) to sync the project branch if it has fallen behind the main branch.

### CODE REVIEW

**Comment by basil** [comment]
CC @krisstern

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by basil** [comment]
One of the reasons that we have to do this in a GitHub Actions workflow rather than in Jenkins is [JENKINS-43749](https://issues.jenkins.io/browse/JENKINS-43749), a ticket that was opened over six (6) years ago and remains unfixed.

**Comment by krisstern** [comment]
Thanks @basil and @MarkEWaite!

**Pull request merged**
