### PR TITLE
gitlabMergeRequestIid -> gitlabMergeRequestId in README.md 

### PR DESCRIPTION
**Pull request by yaooqinn**
gitlabMergeRequestIid -> gitlabMergeRequestId

### CODE REVIEW

**Review by mreichel — APPROVED** [review]

**Comment by omehegan** [comment]
@yaooqinn are you sure this change is correct? gitlabMergeRequestIid is a valid variable, and is different from gitlabMergeRequestId. One of these is a project-scoped ID and the other is global to the GitLab instance.

**Comment by omehegan** [comment]
@yaooqinn ping?

**Comment by nianglao** [comment]
The same question as @omehegan for @yaooqinn. I read existing config for jenkins pipepline in our project and find 'gitlabMergeRequestIid' variable, but find 'gitlabMergeRequestId' in README. I first thought it's a bug, but 'gitlabMergeRequestIid' works fine as we need while 'gitlabMergeRequestId' not.

**Comment by yaooqinn** [comment]
@nianglao @omehegan my mistake，this one should be  reverted

**Comment by omehegan** [comment]
Thanks, I changed this back in master.

**Pull request merged**
