### PR TITLE
[JENKINS-73344] Adapt GitLab for Jetty 12 (EE 9)

### PR DESCRIPTION
**Pull request by basil**
See [JENKINS-73344](https://issues.jenkins.io/browse/JENKINS-73344).

### CODE REVIEW

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by basil** [comment]
Thanks @krisstern! Can this please be released?

**Comment by krisstern** [comment]
Sure @basil! Let me make a release now

**Comment by basil** [comment]
Thank you very much!

**Comment by daniel-beck** [comment]
This change broke `mvn hpi:run`:

```
[WARNING] Failed startup of context o.e.j.m.p.MavenWebAppContext@3e752d61{Jenkins v2.475,/jenkins,file:///Users/danielbeck/Repositories/github.com/jenkinsci/gitlab-plugin/target/jetty/webapp/,UNAVAILABLE}{/Users/danielbeck/.m2/repository/org/jenkins-ci/main/jenkins-war/2.475/jenkins-war-2.475.war}
java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener
    at java.lang.ClassLoader.defineClass1 (Native Method)
    at java.lang.ClassLoader.defineClass (ClassLoader.java:1017)
    at java.security.SecureClassLoader.defineClass (SecureClassLoader.java:150)
    at java.net.URLClassLoader.defineClass (URLClassLoader.java:524)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:427)
    at java.net.URLClassLoader$1.run (URLClassLoader.java:421)
    at java.security.AccessController.doPrivileged (AccessController.java:712)
    at java.net.URLClassLoader.findClass (URLClassLoader.java:420)
    at org.eclipse.jetty.webapp.WebAppClassLoader.foundClass (WebAppClassLoader.java:594)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadAsResource (WebAppClassLoader.java:567)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass (WebAppClassLoader.java:502)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:525)
```

**Comment by krisstern** [comment]
@basil Could you please take a look?

**Comment by basil** [comment]
You'll need to run Maven with `-Dhpi-plugin.version=3.58` until https://github.com/jenkinsci/plugin-pom/pull/1004 is released and adopted.

**Comment by basil** [comment]
Fixed in #1702

**Pull request merged**
