### PR TITLE
[BIS] Fix issue #506 : GitlabCommitStatus throws error after force kill

### LINKED ISSUE #506: GitlabCommitStatus throws error after force kill
### Context
- **Gitlab plugin version**: 1.4.4
- **Gitlab version**: 8.15.3
- **Jenkins version**: 2.40
- **Job type**: Multibranch Pipeline

 ### Logs &  Traces

```
hudson.remoting.ProxyException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A just-in-time binding to com.dabsquared.gitlabjenkins.workflow.GitLabBuildsStep was already configured on a parent injector.
  at org.jenkinsci.plugins.workflow.steps.ContextParameterModule.configure(ContextParameterModule.java:45)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:226)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:233)
	at jenkins.ProxyInjector.createChildInjector(ProxyInjector.java:110)
	at org.jenkinsci.plugins.workflow.steps.AbstractStepImpl.prepareInjector(AbstractStepImpl.java:28)
	at org.jenkinsci.plugins.workflow.steps.AbstractStepImpl.start(AbstractStepImpl.java:21)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:182)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:108)
	at groovy.lang.GroovyObject$invokeMethod.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:151)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:21)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:115)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:149)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:146)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:123)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:16)
	at WorkflowScript.run(WorkflowScript:27)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor550.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:328)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:80)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:240)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:228)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

### Problem description
When a job that uses the plugin is killed, it will try to graceful terminate steps. But when the build is `forcibly killed`, the next time the build will fail on the [gitlabCommitstatus](#logs-traces)

```
Click here to forcibly terminate running steps
Aborted by Someone
[Pipeline] }
Click here to forcibly terminate running steps
Terminating gitlabCommitStatus
Click here to forcibly kill entire build
Terminating gitlabCommitStatus
Hard kill!
```

### LINKED ISSUE #618: Provide release with fix for issue 506
## Issue
Create a new release including merge https://github.com/jenkinsci/gitlab-plugin/pull/548 which is issue https://github.com/jenkinsci/gitlab-plugin/issues/506

### Context
- **Gitlab plugin version**: 1.4.8
- **Gitlab version**:  8.15.3
- **Jenkins version**: 2.40
- **Job type**: Pipeline

### Problem description

Would like to request that a new release with this fix is performed. According to the readme, it should just be `mvn release:prepare release:perform`

cc @omehegan

### PR DESCRIPTION
**Pull request by sbrassely**
Duplicate from PR #548

Fix CreationException when resuming inside script. Fixes #506.
Fixes #618.

### CODE REVIEW

**Comment by omehegan** [comment]
Thanks @sbrassely! I will get this merged after #614 is done.

**Comment by omehegan** [comment]
@sbrassely can you fix merge conflicts? Then we are ready to release this.

**Comment by omehegan** [comment]
@sbrassely ping?

**Comment by sbrassely** [comment]
@omehegan Sorry I had a lot of work lately, i'll check that this week

**Comment by omehegan** [comment]
@sbrassely :) people still asking for this in #506.

**Comment by sbrassely** [comment]
@omehegan I'm done. Sorry for the elapsed time

**Comment by omehegan** [comment]
This was just fixed/released in version 1.5.3 of the plugin. It should be in the update center within a few hours.

**Pull request merged**
