### PR TITLE
[JENKINS-73135] Require Jenkins 2.472, adapt tests for Jetty 12 EE 8

### PR DESCRIPTION
**Pull request by ampuscas**
### Testing done

Automated tests pass on Linux with Java 21.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks for the pull request @ampuscas .  I pushed two changes to the pull request so that it compiles and passes tests on my local installation.  The comments in the changes should explain why I thought they would help.  Refer to:

* e7a0b0887c6957b0573b441e94e175a61b5d37a4 - Use newer Jenkins LTS baseline for BOM
* c169b4fc4b8b7d0d6e8244f47fab015319fafcd1 - Format with spotless

**Comment by MarkEWaite** [comment]
@krisstern I think that we should increment the minor number from 1.8.x to 1.9.0 when merging this pull request, because it changes the minimum Jenkins version and it switches from Java 11 compilation to Java 17 compilation.  Does that match with your thinking or would you prefer something different?

We need to merge and release this before the plugin bill of materials release at the end of this week.

**Review by raul-arabaolaza — APPROVED** [review]
Code looks good to me, but I do not have an idea what is that `jenkins.baseline` property

**Comment by MarkEWaite** [comment]
> Code looks good to me, but I do not have an idea what is that `jenkins.baseline` property

It is used in the Jenkins plugin archetype and in many plugins to avoid duplicating the Jenkins version string in multiple locations.  More information is available in:

* https://github.com/jenkinsci/archetypes/pull/737
* https://github.com/jenkinsci/archetypes/issues/738

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by MarkEWaite** [comment]
Thanks for merging @krisstern !  Are you able to release this as a new version so that it can be updated in the plugin BOM or would you prefer that I create the release?

Should the version number of the new release be 1.9.0 rather than the default of 1.8.3 because the Jenkins minimum version is increased?

**Comment by krisstern** [comment]
Hi @MarkEWaite I am busy with something else now so if you are able to could you please create a new release? Thanks!

**Comment by MarkEWaite** [comment]
Release 1.9.0 is building now.

**Comment by MarkEWaite** [comment]
[Release 1.9.0](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.9.0) is published.

**Pull request merged**
