### PR TITLE
Instead of adding a comment, add an actual vote. #556

### LINKED ISSUE #556: "Add vote" action adds comment instead of voting
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.1.4
- **Jenkins version**: 2.46.2
- **Job type**: Freestyle

### Logs & Traces

```log
May 25, 2017 11:21:06 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic

WebHook called with url: /project/gitlab_merge_request_ci

May 25, 2017 11:21:06 AM FINE com.dabsquared.gitlabjenkins.webhook.build.PushBuildAction

Push: {
  "object_kind" : "push",
  "event_name" : "push",
  "before" : "0000000000000000000000000000000000000000",
  "after" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "ref" : "refs/heads/jenkins_gitlab_plugin",
  "checkout_sha" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "message" : null,
  "user_id" : 14,
  "user_name" : "jostyee",
  "user_email" : "jostyee@mycompany.com",
  "user_avatar" : "https://gitlab.mycompany.com/uploads/user/avatar/14/avatar.png",
  "project_id" : 253,
  "project" : {
    "name" : "myrepo",
    "description" : "",
    "web_url" : "https://gitlab.mycompany.com/mygroup/myrepo",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "git_http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git",
    "namespace" : "mygroup",
    "visibility_level" : 10,
    "path_with_namespace" : "mygroup/myrepo",
    "default_branch" : "master",
    "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo",
    "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git"
  },
  "commits" : [ {
    "id" : "b41a45f767638e4515d83642ec86d75390bf935d",
    "message" : "Just for test\n",
    "timestamp" : "2017-05-25T11:19:40+08:00",
    "url" : "https://gitlab.mycompany.com/mygroup/myrepo/commit/b41a45f767638e4515d83642ec86d75390bf935d",
    "author" : {
      "name" : "jostyee",
      "email" : "jostyee@mycompany.com"
    },
    "added" : [ ],
    "modified" : [ "README.md" ],
    "removed" : [ ]
  } ],
  "total_commits_count" : 1,
  "repository" : {
    "name" : "myrepo",
    "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "description" : "",
    "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo",
    "git_http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git",
    "git_ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "visibility_level" : 10
  }
}

May 25, 2017 11:21:15 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic

WebHook called with url: /project/gitlab_merge_request_ci

May 25, 2017 11:21:15 AM FINE com.dabsquared.gitlabjenkins.webhook.build.MergeRequestBuildAction

MergeRequest: {
  "object_kind" : "merge_request",
  "user" : {
    "name" : "jostyee",
    "username" : "jostyee",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/14/avatar.png"
  },
  "project" : {
    "name" : "myrepo",
    "description" : "",
    "web_url" : "https://gitlab.mycompany.com/mygroup/myrepo",
    "avatar_url" : null,
    "git_ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "git_http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git",
    "namespace" : "mygroup",
    "visibility_level" : 10,
    "path_with_namespace" : "mygroup/myrepo",
    "default_branch" : "master",
    "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo",
    "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git"
  },
  "object_attributes" : {
    "id" : 1405,
    "target_branch" : "master",
    "source_branch" : "jenkins_gitlab_plugin",
    "source_project_id" : 253,
    "author_id" : 14,
    "assignee_id" : 14,
    "title" : "Just for test",
    "created_at" : "2017-05-25 11:19:56 +0800",
    "updated_at" : "2017-05-25 11:19:56 +0800",
    "milestone_id" : null,
    "state" : "opened",
    "merge_status" : "unchecked",
    "target_project_id" : 253,
    "iid" : 4,
    "description" : "",
    "position" : 0,
    "locked_at" : null,
    "updated_by_id" : null,
    "merge_error" : null,
    "merge_params" : {
      "force_remove_source_branch" : "1"
    },
    "merge_when_pipeline_succeeds" : false,
    "merge_user_id" : null,
    "merge_commit_sha" : null,
    "deleted_at" : null,
    "in_progress_merge_commit_sha" : null,
    "lock_version" : null,
    "time_estimate" : 0,
    "source" : {
      "name" : "myrepo",
      "description" : "",
      "web_url" : "https://gitlab.mycompany.com/mygroup/myrepo",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "git_http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git",
      "namespace" : "mygroup",
      "visibility_level" : 10,
      "path_with_namespace" : "mygroup/myrepo",
      "default_branch" : "master",
      "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo",
      "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git"
    },
    "target" : {
      "name" : "myrepo",
      "description" : "",
      "web_url" : "https://gitlab.mycompany.com/mygroup/myrepo",
      "avatar_url" : null,
      "git_ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "git_http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git",
      "namespace" : "mygroup",
      "visibility_level" : 10,
      "path_with_namespace" : "mygroup/myrepo",
      "default_branch" : "master",
      "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo",
      "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "ssh_url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
      "http_url" : "https://gitlab.mycompany.com/mygroup/myrepo.git"
    },
    "last_commit" : {
      "id" : "b41a45f767638e4515d83642ec86d75390bf935d",
      "message" : "Just for test\n",
      "timestamp" : "2017-05-25T11:19:40+08:00",
      "url" : "https://gitlab.mycompany.com/mygroup/myrepo/commit/b41a45f767638e4515d83642ec86d75390bf935d",
      "author" : {
        "name" : "jostyee",
        "email" : "jostyee@mycompany.com"
      }
    },
    "work_in_progress" : false,
    "total_time_spent" : 0,
    "human_total_time_spent" : null,
    "human_time_estimate" : null,
    "url" : "https://gitlab.mycompany.com/mygroup/myrepo/merge_requests/4",
    "action" : "open"
  },
  "labels" : [ ],
  "repository" : {
    "name" : "myrepo",
    "url" : "git@gitlab.mycompany.com:mygroup/myrepo.git",
    "description" : "",
    "homepage" : "https://gitlab.mycompany.com/mygroup/myrepo"
  },
  "assignee" : {
    "name" : "jostyee",
    "username" : "jostyee",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/14/avatar.png"
  }
}

May 25, 2017 11:21:15 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle

gitlab_merge_request_ci triggered for merge request.

May 25, 2017 11:21:15 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:15 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [549],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:19:57 GMT],
Etag = [W/"3f13b90df154dd5eb1f891e638de219b"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [9244e3db-2d06-4bb2-a484-0f908f7b4209],
X-Runtime = [0.082755]
]
Response body: {
  "id" : 1024,
  "sha" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "ref" : "jenkins_gitlab_plugin",
  "status" : "pending",
  "name" : "jenkins",
  "target_url" : "https://ci.mycompany.com/job/gitlab_merge_request_ci/170/",
  "description" : null,
  "created_at" : "2017-05-25T11:19:57.363+08:00",
  "started_at" : null,
  "finished_at" : null,
  "allow_failure" : false,
  "coverage" : null,
  "author" : {
    "name" : "marvin_bot",
    "username" : "marvin",
    "id" : 42,
    "state" : "active",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/42/avatar.png",
    "web_url" : "https://gitlab.mycompany.com/marvin"
  }
}

May 25, 2017 11:21:25 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

May 25, 2017 11:21:25 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: GET
URL: https://gitlab.mycompany.com/api/v3/projects/253/repository/commits/b41a45f767638e4515d83642ec86d75390bf935d
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:26 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/repository/commits/b41a45f767638e4515d83642ec86d75390bf935d
Status: 200 OK
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [512],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:07 GMT],
Etag = [W/"e9e34608e936fc16f25e5b9e149ede65"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [a43d039f-0035-4f98-bbf8-f6422594ba1f],
X-Runtime = [0.117879]
]
Response body: {
  "id" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "short_id" : "b41a45f7",
  "title" : "Just for test",
  "created_at" : "2017-05-25T11:19:40.000+08:00",
  "parent_ids" : [ "f335e86fba3533d6d7e56fa83ff5037d4c1b1e76" ],
  "message" : "Just for test\n",
  "author_name" : "jostyee",
  "author_email" : "jostyee@mycompany.com",
  "authored_date" : "2017-05-25T11:19:40.000+08:00",
  "committer_name" : "jostyee",
  "committer_email" : "jostyee@mycompany.com",
  "committed_date" : "2017-05-25T11:19:40.000+08:00",
  "stats" : {
    "additions" : 2,
    "deletions" : 0,
    "total" : 2
  },
  "status" : "pending"
}

May 25, 2017 11:21:26 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:26 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [576],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:07 GMT],
Etag = [W/"a8ace1b44c6e0b3578472f615e8d1980"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [ec4f274d-c5ae-4ad3-be17-94f704ed3b1e],
X-Runtime = [0.070860]
]
Response body: {
  "id" : 1024,
  "sha" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "ref" : "jenkins_gitlab_plugin",
  "status" : "running",
  "name" : "jenkins",
  "target_url" : "https://ci.mycompany.com/job/gitlab_merge_request_ci/170/",
  "description" : null,
  "created_at" : "2017-05-25T11:19:57.363+08:00",
  "started_at" : "2017-05-25T11:20:07.886+08:00",
  "finished_at" : null,
  "allow_failure" : false,
  "coverage" : null,
  "author" : {
    "name" : "marvin_bot",
    "username" : "marvin",
    "id" : 42,
    "state" : "active",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/42/avatar.png",
    "web_url" : "https://gitlab.mycompany.com/marvin"
  }
}

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.mycompany.com/api/v3/projects/253/merge_requests/1405/notes
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/merge_requests/1405/notes
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [605],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:30 GMT],
Etag = [W/"aa0afe265ebc68a22561f143ad7dc02b"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [5cac3e5c-5296-49b2-9c37-d7ef4055f5fa],
X-Runtime = [0.128564]
]
Response body: {
  "id" : 11795,
  "body" : ":white_check_mark: Jenkins Build SUCCESS\n\nResults available at: [Jenkins [gitlab_merge_request_ci #170]](https://ci.mycompany.com/job/gitlab_merge_request_ci/170/)",
  "attachment" : null,
  "author" : {
    "name" : "marvin_bot",
    "username" : "marvin",
    "id" : 42,
    "state" : "active",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/42/avatar.png",
    "web_url" : "https://gitlab.mycompany.com/marvin"
  },
  "created_at" : "2017-05-25T11:20:30.816+08:00",
  "updated_at" : "2017-05-25T11:20:30.816+08:00",
  "system" : false,
  "noteable_id" : 1405,
  "noteable_type" : "MergeRequest",
  "upvote?" : false,
  "downvote?" : false
}

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.mycompany.com/api/v3/projects/253/merge_requests/1405/notes
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/merge_requests/1405/notes
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [441],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:30 GMT],
Etag = [W/"752577d69096c10c3037f66e7844aad8"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [30ed707c-7518-4e07-aa6e-918cdd76ec2e],
X-Runtime = [0.106786]
]
Response body: {
  "id" : 11796,
  "body" : ":+1:",
  "attachment" : null,
  "author" : {
    "name" : "marvin_bot",
    "username" : "marvin",
    "id" : 42,
    "state" : "active",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/42/avatar.png",
    "web_url" : "https://gitlab.mycompany.com/marvin"
  },
  "created_at" : "2017-05-25T11:20:30.935+08:00",
  "updated_at" : "2017-05-25T11:20:30.935+08:00",
  "system" : false,
  "noteable_id" : 1405,
  "noteable_type" : "MergeRequest",
  "upvote?" : false,
  "downvote?" : false
}

May 25, 2017 11:21:49 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: GET
URL: https://gitlab.mycompany.com/api/v3/projects/253/repository/commits/b41a45f767638e4515d83642ec86d75390bf935d
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/repository/commits/b41a45f767638e4515d83642ec86d75390bf935d
Status: 200 OK
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [512],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:31 GMT],
Etag = [W/"ae0b7ad2b3408d7b20b61c09b1503fb0"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [8a5df4f4-1913-4b5c-bf4a-c920cc14b174],
X-Runtime = [0.094259]
]
Response body: {
  "id" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "short_id" : "b41a45f7",
  "title" : "Just for test",
  "created_at" : "2017-05-25T11:19:40.000+08:00",
  "parent_ids" : [ "f335e86fba3533d6d7e56fa83ff5037d4c1b1e76" ],
  "message" : "Just for test\n",
  "author_name" : "jostyee",
  "author_email" : "jostyee@mycompany.com",
  "authored_date" : "2017-05-25T11:19:40.000+08:00",
  "committer_name" : "jostyee",
  "committer_email" : "jostyee@mycompany.com",
  "committed_date" : "2017-05-25T11:19:40.000+08:00",
  "stats" : {
    "additions" : 2,
    "deletions" : 0,
    "total" : 2
  },
  "status" : "running"
}

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Call GitLab:
HTTP method: POST
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Request headers: [
Accept = [application/json],
Content-Type = [application/x-www-form-urlencoded],
PRIVATE-TOKEN = [****FILTERED****]
]

May 25, 2017 11:21:49 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder

Got response from GitLab:
URL: https://gitlab.mycompany.com/api/v3/projects/253/statuses/b41a45f767638e4515d83642ec86d75390bf935d
Status: 201 Created
Response headers: [
Cache-Control = [max-age=0, private, must-revalidate],
Connection = [keep-alive],
Content-Length = [603],
Content-Type = [application/json],
Date = [Thu, 25 May 2017 03:20:31 GMT],
Etag = [W/"5e2face9708ba219742104b35f9dca80"],
Strict-Transport-Security = [max-age=31536000;],
Vary = [Origin],
X-Request-Id = [3f1226ea-a5fb-4477-ae76-12274cbdb83b],
X-Runtime = [0.078891]
]
Response body: {
  "id" : 1024,
  "sha" : "b41a45f767638e4515d83642ec86d75390bf935d",
  "ref" : "jenkins_gitlab_plugin",
  "status" : "success",
  "name" : "jenkins",
  "target_url" : "https://ci.mycompany.com/job/gitlab_merge_request_ci/170/",
  "description" : null,
  "created_at" : "2017-05-25T11:19:57.363+08:00",
  "started_at" : "2017-05-25T11:20:07.886+08:00",
  "finished_at" : "2017-05-25T11:20:31.148+08:00",
  "allow_failure" : false,
  "coverage" : null,
  "author" : {
    "name" : "marvin_bot",
    "username" : "marvin",
    "id" : 42,
    "state" : "active",
    "avatar_url" : "https://gitlab.mycompany.com/uploads/user/avatar/42/avatar.png",
    "web_url" : "https://gitlab.mycompany.com/marvin"
  }
}
```

### Problem description

_Describe your problem in a meaningful way_:
- what were you doing (simple push, merge request, MR with fork, ...)

    Trigger a Jenkins job with new GitLab MR, which include a post-build action "Add vote for build status on GitLab merge requests"

- what was expected

    Add count to the thumbs up/down icon on the MR

- what occurred finally

    The user add a comment with thumbs up/down under the MR
    screen shot 2017-05-19 at 8 11 29 am
    screen shot 2017-05-19 at 8 11 38 am

### PR DESCRIPTION
**Pull request by deepy**
This fixes #556 but I currently don't have tests covering the functionality for removing an old vote.

### CODE REVIEW

**Comment by deepy** [comment]
I've added a test for removing old votes, it's not the most elegant but now there's test coverage for everything.

**Comment by deepy** [comment]
@Argelbargel any chance of getting a review of this?

We're eagerly awaiting getting this into production :-)

**Comment by omehegan** [comment]
@Argelbargel any chance you can review this? I would like to merge it, but it's too big of a change for me to pull in without someone else looking at it.

**Comment by deepy** [comment]
@omehegan it might be easier to review just GitLabVotePublisher and GitLabVotePublisherTest since just seems to be necessary glue for the API-calls.

If you're ever bored some day we could try the VS code live share and do a remote peer-review on it :^)

**Comment by alejandrovelez7** [comment]
+1 for getting this merged if possible

**Comment by omehegan** [comment]
@MinjunYu you recently mentioned being interested in helping out with this plugin. If you're still up for it, I would love to have someone else review some of the open PRs like this one.

**Comment by omehegan** [comment]
Seeking people to test http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.5.6-SNAPSHOT/gitlab-plugin-1.5.6-20180628.021351-4.hpi and let me know if they encounter issues. If not I will merge.

**Comment by MinjunYu** [comment]
Hi Owen,

I am still trying to understand the code base. It has taken some time
because recently I have a couple of deadlines to meet at work.
I will definitely review the PRs. Thank you for this awesome opportunity.

Minjun

**Comment by padyx** [comment]
I've tested the version you posted (1.5.6-SNAPSHOT (private-1a5991bc-owen)) on GitLab.com (sorry for probably spamming you with notifications).

- The vote post-build action seems to fail. No vote is shown on GitLab.com on my project. Also, the message below is shown in the Jenkins log.
- The "publish status" post-build action is working properly, which means the connection to GitLab.com is working.

```
Jul 17, 2018 12:24:51 AM INFO com.dabsquared.gitlabjenkins.webhook.GitLabWebHook getDynamic

WebHook called with url: /project/mrtest

Jul 17, 2018 12:24:51 AM INFO com.dabsquared.gitlabjenkins.trigger.handler.AbstractWebHookTriggerHandler handle

mrtest triggered for note.

Jul 17, 2018 12:25:01 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds

Retrieving gitlab project ids

Jul 17, 2018 12:25:07 AM INFO hudson.model.Run execute

mrtest #7 main build action completed: SUCCESS

Jul 17, 2018 12:25:08 AM SEVERE com.dabsquared.gitlabjenkins.publisher.GitLabVotePublisher perform

Failed to add vote on Merge Request for project '2283198'
javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:201)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy84.awardMergeRequestEmoji(Unknown Source)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.awardMergeRequestEmoji(ResteasyGitLabClient.java:90)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$13.execute(AutodetectingGitLabClient.java:187)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$13.execute(AutodetectingGitLabClient.java:184)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:341)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
	at com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.awardMergeRequestEmoji(AutodetectingGitLabClient.java:183)
	at com.dabsquared.gitlabjenkins.publisher.GitLabVotePublisher.perform(GitLabVotePublisher.java:74)
	at com.dabsquared.gitlabjenkins.publisher.MergeRequestNotifier.perform(MergeRequestNotifier.java:39)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by omehegan** [comment]
Maybe there is something different about gitlab.com. They will be running the near-latest release of CE I think, so 11.x. @deepy any thoughts?

**Comment by deepy** [comment]
Hmm, I'm getting the same locally.

Must've gotten something wrong somehow, will investigate and push a fix

**Comment by deepy** [comment]
Oops, tested on the wrong server, it is in fact working fine locally, it's just that my GitLab connection was to the staging area and not test.

Will test with gitlab.com as soon as my public-facing jenkins is updated.

**Comment by deepy** [comment]
Well this is interesting, it works fine on self-hosted gitlab. And adding notes works on gitlab.com, but awarding emoji gives a 404.

**Comment by deepy** [comment]
Ok. I've found the cause, you're unable to give thumbsup/thumbsdown on your own merge request. So if you created the merge request and use your own API key you'll get a 404 when trying to thumbsup/thumbsdown.

Not entirely sure what a good way to signal this to the user is. But apart from that (which can never work) the plugin seems to work. @omehegan @padyx

I'm thinking the best might be to catch the NotFoundException here and warn if it happens, but I'm open to suggestions

https://gitlab.com/deepy/mr-test/merge_requests/1 - failure

https://gitlab.com/deepy/mr-test/merge_requests/2 - success

**Comment by padyx** [comment]
@deepy A weird API design quirk indeed. I think a warning in the log would be appropriate. Something in the line of "GitLab merge request vote failed: The configured credentials belong to the author of the merge request, who is not allowed to vote on his own merge request."

I've cajoled a colleague into making another GitLab.com account to test this with 2 accounts and now it seems to work. I've tested this on GitLab.com:
- A build getting a vote up / vote down properly shows up in the GitLab interface.
- A reversal by the next build to the opposite correctly changes the vote from up to down, and vice versa

Success!

**Comment by deepy** [comment]
I was thinking something easier, that doesn't rely on having to parse the message from their 404.

Something like: "Got a 404, are you using the wrong API version or trying to vote on your own merge request?"

**Comment by omehegan** [comment]
@deepy thanks for looking into this, I leave it to you to decide how to resolve. An error with "maybe it could be this" output seems reasonable, Jenkins does that type of thing in other places.

**Comment by deepy** [comment]
```java
catch (NotFoundException e) {
            String message = String.format("Failed to add vote on Merge Request for project '%s'\n" +
                "Got unexpected 404, are you using the wrong API version or trying to vote on your own merge request?", mergeRequest.getProjectId());
            listener.getLogger().println(message);
            LOGGER.log(Level.WARNING, message, e);
}
```

Warning has been added, the delete path should be safe since we shouldn't be able to find anything we can't delete.

**Comment by omehegan** [comment]
I've published another snapshot with this fix: http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/plugins/gitlab-plugin/1.5.6-SNAPSHOT/gitlab-plugin-1.5.6-20180719.035553-5.hpi 

@padyx could you confirm this is working?

**Comment by padyx** [comment]
@omehegan I've tested your new build (1.5.6-SNAPSHOT (private-1824374c-owen)) vs GitLab.com and Jenkins 2.121.1 and everything works as expected:

- Upvote / Downvote get added
- If rebuilt with a different results in the other vote being removed
- Rebuilding with same result has no unexpected effect.
- If (and only if) the credentials match the author or the MR, the 404-message specified by @deepy is shown.

(I've also tested the "Publish build status to GitLab" as a regression test, which works too.)

I've encountered an intermittent network error causing the "opposing" vote to stay (up & down vote at same time present), which was solved by retriggering the build. The plugin properly warned about this in the build log and printed the trace into the Jenkins Global Log.

Looks good to me :)

**Comment by omehegan** [comment]
@padyx thanks so much for the thorough testing, I really appreciate it!
@deepy thanks again for the fix!

**Comment by padyx** [comment]
Happy to help :)
Thanks for all your work guys, both of you!

**Comment by omehegan** [comment]
This was released in version 1.5.9 of the plugin.

**Pull request merged**
