### PR TITLE
Add help for many options

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Add online help for many options

Correct errors in capitalization of GitLab

- Capitalize GitLab correctly in multiple locations

Add help in multiple locations

- Add apiTokenID help
- Add API level help
- Help for connection timeout
- Describe the ignore SSL certificate errors checkbox
- Describe the name field
- Describe the read timeout
- Describe URL field
- Add help for the authenticated end-pont checkbox
- Add global help (not visible from the UI)
- More help
- Add help for several trigger settings
- Add help for labels that force builds
- Add help for some of advanced trigger options
- Add help for cancel pending builds on merge request update

Feel free to squash merge this.  The individual commits were small stepping stones while I was experimenting with the plugin

### CODE REVIEW

**Comment by krisstern** [comment]
@harsh-ps-2003 Just checking to see if I merge this now will you be able to incorporate the changes in your GSoC PRs in a timely manner?

**Comment by krisstern** [comment]
Thanks @MarkEWaite for this PR!

**Comment by harsh-ps-2003** [comment]
@krisstern is there any urgency to merge this PR? I would suggest that it gets merged after completion of Milestone 2. I would prefer all docs related PRs to be merged at similar time.

**Comment by krisstern** [comment]
@MarkEWaite I will review this over the next few days

**Comment by krisstern** [comment]
> @krisstern is there any urgency to merge this PR? I would suggest that it gets merged after completion of Milestone 2. I would prefer all docs related PRs to be merged at similar time.

Sure, I can review it first and wait until after the completion of Milestone 2 to merge.

**Comment by krisstern** [comment]
@harsh-ps-2003 Just wanted to let you know that we will approve and possibly merge this PR over the next few days, contrary to what I have stated earlier. It is because after some reflection it is deemed the progress of the ongoing GSoC project should not interfere with the normal maintenance and operation of the running of the plugin project. I will cut a release of the plugin soon also.

**Review by krisstern — APPROVED** [review]
LGTM! Thanks @MarkEWaite

**Pull request merged**
