### PR TITLE
Add getter to triggerOnApprovedMergeRequest

### LINKED ISSUE #711: Approved Merge Requests (EE-only) is not persisted
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 10.3.5
- **Jenkins version**: 2.89.3
- **Job type**: Freestyle

### Problem description

The plugin doesn't respect a flag for 
<f:entry title="Approved Merge Requests (EE-only)" field="triggerOnApprovedMergeRequest">

When toggling this setting and applying the change on refresh of the job, the toggle is activated again. 

It should persist the toggle. 

There are no log statements in the Jenkins log.

### PR DESCRIPTION
**Pull request by jakub-bochenski**
Fixes #711

### CODE REVIEW

**Comment by chinhodado** [comment]
Can someone merge this please? The issue is annoying.

**Comment by jakub-bochenski** [comment]
@omehegan @Argelbargel @mreichel the fix is rather simple, can you take a look please?

**Review by Argelbargel — APPROVED** [review]

**Comment by lambourn** [comment]
would be great if the team could cut a hotfix release that incorporates this fix.

**Comment by jakub-bochenski** [comment]
@lambourn  why don't you try the snapshot build and see if it fixes the issue for you? https://ci.jenkins.io/job/Plugins/job/gitlab-plugin/job/PR-714/1/artifact/target/gitlab-plugin-1.5.4-SNAPSHOT.hpi

**Comment by lambourn** [comment]
@jakub-bochenski will definitely do, I was not aware there is a snapshot for it.

**Comment by chinhodado** [comment]
~~I~~ ~~can~~ ~~confirm~~ ~~the~~ ~~snapshot~~ ~~fixes~~ ~~the~~ ~~issue~~

Edit: it doesn't, see below.

**Comment by williamzhao87** [comment]
Can someone merge this if possible? Would be great to have the fix available :)

**Comment by chinhodado** [comment]
Actually I think it doesn't fix the issue. With the snapshot build, the checkbox for "Approved Merge Requests" is properly cleared when loading the config page, but the build is still triggered when that event happens.

**Comment by sulx** [comment]
Yea triggerOnApprovedMergeRequest as false it now goes off but still triggers on approval

**Comment by pdudits** [comment]
I think these are identified as two separate issues. #711 is UI issue, #633 is the actual problem with missing filters for job triggers.

**Comment by omehegan** [comment]
This was fixed/released in version 1.5.4 of the plugin, which should be available in the update center soon.

**Pull request merged**
