### PR TITLE
Use GitLab's host url to calculate project's ID

### LINKED ISSUE #538: Cannot update commit-status of project in subgroup
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 9.0.5-ee
- **Jenkins version**: 2.7.2
- **Job type**: multibranch pipeline

### Logs & Traces

Added Jenkins logger for `com.dabsquared.gitlabjenkins`, level `ALL`. Replaced host and group names with `on.premises`, `groupname`, `subgroupname`, `projectname`:
```
Apr 18, 2017 8:17:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving gitlab project ids
Apr 18, 2017 8:17:02 AM INFO com.dabsquared.gitlabjenkins.util.CommitStatusUpdater retrieveGitlabProjectIds
Retrieving the gitlab project id from remote url git@on.premises:groupname/subgroupname/projectname.git
Apr 18, 2017 8:17:02 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Call GitLab:
HTTP method: GET
URL: https://on.premises/api/v3/projects/subgroupname%2Fprojectname/repository/commits/904cdaa399aeae7ef8e96b94e884658d11879962
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [****FILTERED****]
]
Apr 18, 2017 8:17:08 AM FINEST com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: https://on.premises/api/v3/projects/subgroupname%2Fprojectname/repository/commits/904cdaa399aeae7ef8e96b94e884658d11879962
Status: 404 Not Found
Response headers: [
Cache-Control = [no-cache],
Connection = [keep-alive],
Content-Length = [35],
Content-Type = [application/json],
Date = [Tue, 18 Apr 2017 06:16:44 GMT],
Server = [nginx],
Vary = [Origin],
X-Request-Id = [fbb2d8c9-1bf4-42cf-a5f6-ca5e70e96256],
X-Runtime = [0.034847]
]
Response body: {
  "message" : "404 Project Not Found"
}
Apr 18, 2017 8:17:08 AM FINE com.dabsquared.gitlabjenkins.util.CommitStatusUpdater
Project (subgroupname/projectname) and commit (904cdaa399aeae7ef8e96b94e884658d11879962) combination not found
```

### Problem description

The plugin does not use the group's name, only the subgroup's name to try and update the commit-status at Gitlab: `.../projects/subgroupname%2Fprojectname/repository/...`
This should be: `.../projects/groupname%2Fsubgroupname%2Fprojectname/repository/...`

### PR DESCRIPTION
**Pull request by axls**
1. Introduces GitLabApi extension by using delegation to the RESTEasy proxy. This extension used to provide GitLab host url (from config) to GitLabApi consumers.
2. Uses GitLab host's base url (when available) to build project's id. By using host's url we may subtract baseUrl from remoteUrl and get relative project's url, including groups and subgroups, but excluding GitLab hos context url. 

Allows Jenkins to send build results to GitLab projects that are in subgroups.

Fixes #538.

### CODE REVIEW

**Comment by omehegan** [comment]
@axls can you resolve the merge conflicts?

**Comment by axls** [comment]
@omehegan 
> can you resolve the merge conflicts?

done

**Comment by omehegan** [comment]
@axls can you resolve conflicts again? Then I will work on reviewing and merging this. Thanks :)

**Comment by omehegan** [comment]
@axls ping?

**Comment by axls** [comment]
@omehegan Sorry, was on vacation and missed the notification. I'll look into it today.

**Comment by axls** [comment]
@omehegan 

> can you resolve conflicts again?

done

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Pull request merged**
