### PR TITLE
PCT compatibility with recent core releases

### PR DESCRIPTION
**Pull request by basil**
### Before submitting a pull request, please make sure you read the instructions in the ["Contribution to the Plugin"](https://github.com/jenkinsci/gitlab-plugin/tree/master#contributing-to-the-plugin) section in the README.

*(if you read the above instructions, remove the paragraph and start describing the pull request)*

### CODE REVIEW

**Comment by basil** [comment]
This looks ready for merge to me, assuming the baseline bump is OK. This change basically adapts to the Guava upgrade by cleaning up the build to remove the old version of Guava.

**Comment by MarkEWaite** [comment]
> This looks ready for merge to me, assuming the baseline bump is OK. This change basically adapts to the Guava upgrade by cleaning up the build to remove the old version of Guava.

Baseline bump makes sense to me.  

The [current guidelines](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) recommend 2.332.4 rather than 2.332.1.  I'm ready to merge it if with either 2.332.1 or 2.332.4 as the baseline.

**Comment by basil** [comment]
commit a2001e9

**Review by MarkEWaite — APPROVED** [review]
Ready to merge.  Thanks!

**Pull request merged**
