### PR TITLE
Trigger build only when new commits were pushed to MR

### PR DESCRIPTION
**Pull request by ababushk**
This PR resolves the problem described in #871 and #926 
An option in trigger configuration was added - when set build will be started on MR update only if it has new commits pushed to source branch. However, in current implementation build won't start when work in progress merge request become non-WIP MR.
I can use some help to write tests and fix the issue with WIP merge requests.

### CODE REVIEW

**Comment by ababushk** [comment]
Hi @anton-johansson! Thank you very much for changes introduced in #903! They were exactly what I needed to finish this PR and I had no idea how to implement them by myself. If you have some spare time I humbly ask you to review this PR because I think it can interfere with your changes (I've tried to resolve conflicts as accurate as possible)

**Comment by ababushk** [comment]
@anton-johansson it did interfere with your changes, so I slightly changed a condition and now MR will be built anyway if force build labels were set

**Comment by slyalin** [comment]
Can we assign someone to review and merge changes? It is a very desired fix.

**Comment by ababushk** [comment]
@markyjackson-taulia can you please take a look?

**Comment by ababushk** [comment]
Thank you @markyjackson-taulia !

**Comment by sandeepnagori87** [comment]
@ababushk was this issue "However, in current implementation build won't start when work in progress merge request become non-WIP MR." fixed as well?

I see that when we move MR from "WIP" to Ready, pipeline does not start

**Comment by ababushk** [comment]
@sandeepnagori87 It's been a while, so I don't remember details, but according to https://github.com/jenkinsci/gitlab-plugin/blob/76afae8818251c9072fc8cb8a4c868902148c06d/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/merge/MergeRequestHookTriggerHandlerImpl.java#L260 it was fixed and should work.

**Pull request merged**
