### PR TITLE
Fix "Test Connection" button when used with Jackson 2.16.1 or later

### LINKED ISSUE #1605: The test connection button on Jenkins' configure page throws Client error: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.2
OS: Linux - 4.14.330-250.540.amzn2.x86_64
Java: 11.0.20 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
git:5.2.1
git-client:4.6.0
github:1.37.3.1
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1767.va_7d01ea_c7256
gitlab-plugin:1.7.18
jackson2-api:2.16.1-373.ve709c6871598
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux 2

### Reproduction steps

1. Install latest version of jackson2-api plugin (2.16.1-373.ve709c6871598) + gitlab-plugin
2. Navigate to configure page
3. Setup a gitlab connection
4. Press Test Connection button

### Expected Results

Success message should display.
Expected-GitLab-Connection-Test

### Actual Results

Error msg displays: Client error: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
Actual-GitLab-Connection-Test

### Anything else?

Related to [JENKINS-72478](https://issues.jenkins.io/browse/JENKINS-72478) Jackson2 API 2.16.1 removes Java PropertyNamingStrategy aliases

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by bruderol**
Here is a pull request for the proposed solution as proposed and discussed on the issue #1605 - would be great if you could release that soon please.

### Testing done?

When the most recent Jackson 2 API plugin (2.16.1.x) is used, compilation fails without this change and succeeds with this change.  Interactive testing of the "Test connection" button confirms that the new code is well behaved

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x]  Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Passed my interactive testing of the "Test connection" button.  I was able to see the problem without this change and was able to confirm the problem is fixed with this change.

**Comment by MarkEWaite** [comment]
@krisstern and @harsh-ps-2003 I think that we should merge the pull requests and deliver the 1.8.0 release of the GitLab plugin.  The pull requests are:

* #1606
* #1607 

Does that seem reasonable for the two of you?

**Comment by MarkEWaite** [comment]
Thanks @bruderol.  Can you deploy the build from ci.jenkins.io on your Jenkins controller and confirm with interactive testing that the previously visible problem is resolved?

**Comment by krisstern** [comment]
> @krisstern and @harsh-ps-2003 I think that we should merge the pull requests and deliver the 1.8.0 release of the GitLab plugin. The pull requests are:
> 
> * [Fix "Test Connection" button when used with Jackson 2.16.1 or later #1606](https://github.com/jenkinsci/gitlab-plugin/pull/1606)
> * [Require Jenkins 2.401.3 or newer #1607](https://github.com/jenkinsci/gitlab-plugin/pull/1607)
> 
> Does that seem reasonable for the two of you?

Sure, this makes sense to me

**Comment by MarkEWaite** [comment]
> Sure, this makes sense to me

Thanks.  I'll plan to generate a release in a few hours.

**Comment by bruderol** [comment]
@MarkEWaite wow, I am impresed - thank you for testing and releasing it so fast. That was a great experience :-) Will immediately test the new release. Thanks so much.

And I can allready confirm, that the new release does not have that issue anymore. Thank you!

**Pull request merged**
