### PR TITLE
Fix PipelineHookTriggerHandlerImpl, replace `hook.getProjectId()` to `hook.getProject().getId()`

### LINKED ISSUE #723: Build on successful pipeline events
### Context
- **Gitlab plugin version**: 1.5.3
- **Gitlab version**: 9.1.4
- **Jenkins version**: 2.89.4
- **Job type**: Pipeline

### Logs & Traces

Nothing appears in the logs when I perform this action.

### Problem description

_Describe your problem in a meaningful way_:
When I set  *Build on successful pipeline events* on my build trigger and save the job it is unset when I re-open the job.
- what was expected
The setting would persist and my build would be triggered by pipeline events.
- what occurred finally
The setting does not persist.

### PR DESCRIPTION
**Pull request by Moln**
For fix #723

### CODE REVIEW

**Comment by markjacksonfishing** [comment]
@Moln Is there an associated Github issue with this PR? What about a Jenkins jira? If so, can you link them? If not, can you open them and note this PR?
Thank you for that.

**Comment by Moln** [comment]
@markyjackson-taulia 

> Is there an associated Github issue with this PR?

You mean this issus #723 ?

**Comment by zdtsw** [comment]
Can someone approve this MR?

**Comment by zdtsw** [comment]
Thanks @markyjackson-taulia, any plan to release 1.5.17? 
latest released version is 1.5.13 from https://plugins.jenkins.io/gitlab-plugin/

**Comment by markjacksonfishing** [comment]
It has been released but there is a problem with the Jenkins infra and it is not showing in the update center. The release is here: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.17

**Comment by LucasSymons** [comment]
> It has been released but there is a problem with the Jenkins infra and it is not showing in the update center. The release is here: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.17

any chance you can update the changelog?

**Pull request merged**
