### PR TITLE
Add option to filter source branch with regex

### LINKED ISSUE #751: Source Branch Regex
With this plugin, we can filter branches by regex using the "Target Branch Regex" option, but there's no "Source Branch Regex" option. Is there a special reason for that?

I'm currently looking at the code and I will try to implement a "Source Branch Regex" option since I need it for my use case.

### PR DESCRIPTION
**Pull request by sebastienbonami**
Fixes #751

It works, but I didn't adjust any test classes for that. Can somebody do it? Thanks.

### CODE REVIEW

**Comment by omehegan** [comment]
I can't update the tests, but maybe @Argelbargel can do it and also review this PR?

**Comment by breisig** [comment]
Any update on this great feature?

**Comment by omehegan** [comment]
Still needs tests and review. I think @Argelbargel may be too busy these days unfortunately.

**Comment by omehegan** [comment]
@sebastienbonami I've created some merge conflicts, can you resolve them?

**Comment by sebastienbonami** [comment]
@omehegan Merge conflicts resolved. Compilation failures are all in tests.

**Comment by omehegan** [comment]
@sebastienbonami yes, so because in 0a08a28c93f4a30d613ac8570ecee943d62e06f3 you changed isBranchAllowed() to take two arguments, all the tests that only supply one are failing. Can you fix the tests?

**Comment by breisig** [comment]
Yeah, it looks like the tests still need to be updated with the two arguments to pass those tests.

**Comment by omehegan** [comment]
This was released today in 1.5.10.

**Pull request merged**
