### PR TITLE
New feature: Add support for regex based filtering and more

### PR DESCRIPTION
**Pull request by omorillo**
Two new features were introduced:

(1) Allow branch filtering through regular expressions
(2) Use branch filtering also for Merge Request events

By making use of <b>radioBlocks</b> tags, the user is forced to choose
between allowing all branches to trigger the respective job and 
filtering the branches by one out of two possible approaches:
- filtering by name
- filtering by regular expression

### CODE REVIEW

**Comment by sebastienbonami** [comment]
:+1:
This is fixing https://github.com/jenkinsci/gitlab-plugin/issues/142

**Comment by benoitbleuze** [comment]
It would also fix #97. This is also why @omorillo developed this feature, so that we could run different jobs (using different nodes/build setup) for different branches (legacy version maintenance branches, or current development ones).

**Comment by omehegan** [comment]
@omorillo I'm ready to merge this, but I won't have time to test it myself. I assume you've been using this internally? Have you found any issues with it? Thanks!

**Comment by omorillo** [comment]
@omehegan Yes, we've been. So far everything worked fine.

**Comment by omorillo** [comment]
List _fixed_ issues in commit message and rebased on latest master branch.

**Comment by omorillo** [comment]
@jenkinsadmin @omehegan I read the document linked by @jenkinsadmin.

I am comfortable with the changes and in my opinion the merge can be done without any review. I rebased to the latest jenkinsci/gitlab master branch and tested my rebased code again. How should we proceed?

According to the linked document I would now request commit access for this repository and take care myself of performing the merge and creating a new release, is it correct?
If the case, can you give me commit access for the repository of the plugin (_jenkinsci/gitlab_) or do I need to post my request to the jenkinsci dev mailing list as described in the document?

**Comment by omehegan** [comment]
@omorillo normal practice would be for me to merge this PR and perform a release, so I will do that.

If you are interested in becoming a maintainer and helping triage other issues and pull requests, I would be happy to give you commit access so you can do that as well!

**Comment by omorillo** [comment]
Yes, I would like. Thanks.

**Comment by omehegan** [comment]
@omorillo someone helped me resolve the issue I was having with commit access to the plugin, so I can move forward. I also gave you access. Later today I will merge this PR and some others and do a release. If you're willing to help work on other aspects of the plugin, maybe we can find a good place to discuss other features and bug fixes that it needs.

**Comment by omehegan** [comment]
@omorillo I've merged this change and I'm testing it locally, but I'm struggling to get GitLab to trigger a job when I create a new merge request. I don't know if that ever worked, though. Have you tested that path? I can't even figure out what the entry point is in the code for that scenario.

**Comment by mattiasb** [comment]
@omehegan We use this plugin to build merge requests at my work all the time. It works fine.

**Comment by omehegan** [comment]
@mattiasb can you tell me what job type you're using? I wonder if it's only broken for Workflow jobs.

**Comment by mattiasb** [comment]
Just regular manual job types.

**Comment by WonderCsabo** [comment]
@omehegan @mattiasb @omorillo unfortunately i think this PR introduced a regression.

There is no default value for the radioblock. This means if you have already existing  jobs, and update the plugin, you will end up with `branchFilterName` being `null`. Actually i experienced this when testing my PR. I think we should definitely add a default value for these 3 options.

**Comment by omehegan** [comment]
Good catch @WonderCsabo. @omorillo can you add a fix for this?

**Comment by omehegan** [comment]
@mattiasb what version of GitLab are you using? 7.14.3 seems to not even send a request to Jenkins to build when an MR is created.

**Comment by mattiasb** [comment]
@omehegan I'm not at work currently, but I believe it's 8.1.x, and I have "Use GitLab CI features" checked.

**Comment by omorillo** [comment]
@WonderCsabo @omehegan I will have a look at it. Created an issue for this #202.

**Comment by WonderCsabo** [comment]
@olamy great!

**Comment by WonderCsabo** [comment]
@omorillo The [allowed branches help](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/webapp/help/help-allowedBranches.html) talks about the _source_ branch, the [regex based filter help](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/webapp/help/help-filterBranchesByRegex.html) talks about _target_ branches.

I looked at on the code, and it seem the filtering is based on [the _source_ branch with pushes](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/GitLabPushTrigger.java#L234), but on the [_target_ branch on MRs](https://github.com/jenkinsci/gitlab-plugin/blob/master/src/main/java/com/dabsquared/gitlabjenkins/GitLabPushTrigger.java#L364) (regardless of the filter type). It seems everything got mixed up, or i am missing sg?

**Comment by omorillo** [comment]
True, the help docs do not mirror the actual implementation. I will provide a fix for it by tomorrow. Creating issue #221.

**Pull request merged**
