### PR TITLE
Improve Jenkinsfile sample code in README.md

### PR DESCRIPTION
**Pull request by guessi**
Currently, there's no documentation for how to configure [Scripted Jenkinsfile](https://jenkins.io/doc/book/pipeline/syntax/#scripted-pipeline), it would be better to have sample code in README.md

Related: #417

### CODE REVIEW

**Comment by omehegan** [comment]
@guessi thanks for improving this! But I think your diff applies to all scripted Pipeline, not just Multibranch, so I would like to refactor the README further to make that clearer. If you want to do that, feel free, otherwise I will work this into a larger rewrite of this part of the doc.

**Comment by guessi** [comment]
@omehegan good to know it's going to be refactor, but I'm not sure what do you mean by refactor, if it is to rewrite or refactor document structure, I'm afraid I have no time for that ... :'(

**Comment by omehegan** [comment]
@guessi I just mean that your commit edits the part of the README that is specific to Multibranch project. I believe your change applies to any type of Pipeline project, so I want to make sure that is clear to the reader. I will modify it :)

**Comment by guessi** [comment]
Rebase onto current master (80c3786) for fixing merge conflict

**Comment by omehegan** [comment]
@guessi I have just done a major refactor of the README, I think it's must easier to follow now. I specifically reorganized the documentation around Pipeline.

I have looked at your PR again, and I'm a little confused as to whether it is valid or not. Here's why: if the job is a regular, non-multibranch Pipeline, then all of this configuration is exposed in the Jenkins UI. There is no reason you would need to store it in the Jenkinsfile. On the other hand, if the job is a Multibranch type, AFAIK the plugin does not parse the JSON request from GitLab, so none of the data would be read. And thus these settings like ciSkip and possibly even secretToken would be ignored. I need to test this, but I was wondering if you think I've misunderstood something here. Please let me know!

**Comment by guessi** [comment]
@omehegan the original purpose of this PR is to resolve missing example for `Scrippted Pipeline`, the regular Jenkinsfile, and I've checked the sample code in this PR again, there should have NO credential to be shown on the Jenkins WebUI, and I've tested that with/without `secretToken`, `ciSkip` are worked.

**Comment by omehegan** [comment]
@guessi sorry for all the back-and-forth, it had been a few months since I looked at this code and I got myself confused. Your change is correct, I expanded on it and put it in a different part of the README. Thank you!

**Comment by guessi** [comment]
NP 👍

**Pull request closed without merging**
