### PR TITLE
Allow jobs to be triggered by GitLab 'Pipeline' event

### PR DESCRIPTION
**Pull request by mreichel**
This PR implements the feature request [Can the gitlab plugin handle the gitlab's pipeline event？ #461](https://github.com/jenkinsci/gitlab-plugin/issues/461)

### CODE REVIEW

**Comment by omehegan** [comment]
Well done! Maybe @trance1st or @colourmeamused could review this.

**Comment by colourmeamused** [comment]
This looks brilliant - haven't had time to look through it in detail but I'll try to find time soon but I'm good with it being merged if one more person has reviewed.

**Review by colourmeamused — APPROVED** [review]

**Comment by omehegan** [comment]
@mreichel shoot, I might have introduced a merge conflict here...

**Comment by mreichel** [comment]
@omehegan: no worries,  I fixed it

**Comment by valeryq** [comment]
Guys, what is the status of this PR?

**Comment by omehegan** [comment]
@valeryq as you see it :) Not yet merged. I would like for someone else to do a full review, but failing that we may just release it this week and hope for the best.

**Comment by omehegan** [comment]
@valeryq feel free to do a local build of the plugin with this PR merged, install it on your Jenkins, and let us know if it works. That user feedback would be very helpful.

**Comment by jmiserez** [comment]
Does this by any chance also support the "Cancel pipeline" event when you cancel a build in Gitlab?

**Comment by omehegan** [comment]
@mreichel I probably should have included this in today's release but I was anxious to get the things we had already merged out. I'm planning to do at least a monthly release going forward.

Can you remove the edit to the CHANGELOG.md? I usually update that myself with all relevant changes before doing a release, so this diff is now invalid because I've just released 1.4.6.

**Comment by junguchina** [comment]
@mreichel @omehegan Can this request be merged in next version? I want to see this feature in next version, maybe is 1.4.7.
Thanks for your hard work.

**Comment by omehegan** [comment]
@junguchina yes that is my plan.

**Comment by mreichel** [comment]
I added a new commit since I did not want to rebase

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Comment by junguchina** [comment]
@mreichel @omehegan Thank you for your hard work!

**Pull request merged**
