### PR TITLE
Add support for tag_push event from GitLab

### PR DESCRIPTION
**Pull request by bbreijer**
#580 

### Before submitting a pull request, please make sure you read the instructions in the ["Contribution to the Plugin"](https://github.com/jenkinsci/gitlab-plugin/tree/master#contributing-to-the-plugin) section in the README.

*(if you read the above instructions, remove the paragraph and start describing the pull request)*

### CODE REVIEW

**Comment by omehegan** [comment]
@bbreijer can you look at the test failures on this? Perhaps it need a rebase with master.

**Comment by bbreijer** [comment]
@omehegan The tests succeed now, the object kind was missing in the hook builder.

**Comment by omehegan** [comment]
@bbreijer thanks! From what I can tell of the diff, support for tag_push events is added, but there isn't any additional configuration option for it in the UI. So will tags always trigger builds if they are configured to trigger on pushes? It may be that users will want to disable that, and only trigger on code pushes, because that has been the behavior of the plugin until now.

**Comment by bbreijer** [comment]
@omehegan The current behaviour is that the build is triggered on both a tag push and a regular push (if you configured the webhook in gitlab in that way). The only way to obtain the real cause of the build with this configuration is by looking at the branch value, this contains a tag if it was caused by a tag_push.
The changes i implemented make it more easy to distinguish between a regular push and a tag push.

I totally agree that a future improvement would be to add a setting with a tag specifier on which tags to build and not to build, but i think that the setting wether a build should trigger at all is already handled by the GitLab webhook configuration.

**Comment by omehegan** [comment]
@bbreijer ok thanks, now I understand and this makes sense. Can you just clarify what someone would do in their build to make use of this? It's not apparent to me from the diff what they would do to check the cause.

**Comment by bbreijer** [comment]
@omehegan One can use the environment variable `gitlabActionType` to distinguish between a `PUSH` and a `TAG_PUSH`, while this variable is set to `PUSH` in both situations now. The exact use is dependant on your personal situation of course.

**Comment by omehegan** [comment]
@bbreijer aha, thank you, that was the part I was missing. Makes sense! I will merge this, but I am intending to do a release that only contains #614 first, once that is ready. Then I'll get this released.

**Comment by cliles** [comment]
@omehegan - Any updates? TAG_PUSH would be great.

**Comment by omehegan** [comment]
This has just been released in plugin version 1.5.2. It will be in the update center within a few hours.

**Pull request merged**
