### PR TITLE
Fix branch name comparison to avoid spurious builds

### PR DESCRIPTION
**Pull request by czoellin**
Fixes issue #512.

### CODE REVIEW

**Comment by omehegan** [comment]
Thanks! We'll consider this for the next release.

**Comment by omehegan** [comment]
@czoellin is it possible this could break merge request builds, because they may check out refs/merge-requests/*/head ? I'm not totally clear on how this works. But see https://docs.gitlab.com/ee/user/project/merge_requests/index.html

**Comment by omehegan** [comment]
@czoellin ping re: my last comment.

**Comment by czoellin** [comment]
The target branch name that is being compared here is never going to be one of these hidden refs for merge requests. Don't see a problem.

**Comment by omehegan** [comment]
OK, thanks! Will consider this for the next release.

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Pull request merged**
