### PR TITLE
Fix tag ref when setting build status.

### PR DESCRIPTION
**Pull request by jukov**
I have same issue described in #677.

After review pull #774 i figured out not only CommitStatusUpdater update build status, and remove branch ref in other places.

### CODE REVIEW

**Comment by thomas955** [comment]
We had the same issue with Jenkins CI -> and Tag pushing from gitlab.
Like discussed here and in https://github.com/jenkinsci/gitlab-plugin/issues/677 the behaviour is 100% the same. 

I compiled the gitlab plugin with the changes from jukov and for me its working so far. it would be nice if this could be merged as soon as possible into the official gitlab-jenkins plugin

Thanks @jukov

p.s. there is a stackoverflow post with the same problem
https://stackoverflow.com/questions/52933087/double-pipelines-on-gitlab-tag-webhook

**Comment by rlfnb** [comment]
@omehegan Would be great to see it merged, still running into the same problem being described and already fixed in the PR sent by @jukov

**Comment by markjacksonfishing** [comment]
@jukov Is there an associated Github issue with this PR? What about a Jenkins jira? If so, can you link them? If not, can you open them and note this PR?
Thank you for that.

**Comment by thomas955** [comment]
@omehegan Is it possible to merge this into the master soon? Would be nice.
 Thank you in advance.

**Comment by thomas955** [comment]
Just created a ticket in jira: see https://issues.jenkins-ci.org/browse/JENKINS-60233

**Pull request merged**
