### PR TITLE
Do not build approved merge requests unless specified so

### LINKED ISSUE #633: Build triggered needlessly after MR states change
## Issue
Our gitlab is set up so that each merge request must be approved by 1 or 2 reviewers before it can be merged. In addition Jenkins has to successfully build the project with the proposed changes.
When a reviewer hits the "Approve" button, the "Merge Request" webhook is triggerd, causing Jenkins to build the project again, even if it was successfully built previously.

### Context
- **Gitlab plugin version**: 1.4.3
- **Gitlab version**: 9.2.10-ee
- **Jenkins version**: 2.46.2
- **Job type**: Freestyle

### Problem description
Gitlab sends a "Merge Request" json with action "approved".
That action is apparently not evaluated, and it is also not checked whether there were actual changes committed to the feature branch.

Expected:
Hitting "Approve" in Gitlab does not trigger a new build in Jenkins.

### LINKED ISSUE #663: Automatic project creation should work with Jenkins Folders
### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab version**: 10.1.1
- **Jenkins version**: 2.32.3
- **Job type**: Freestyle

### Problem description

We are using Gitlab plugin in order to trigger builds automatically and create jobs on branches creations.
It used to work as expected. But we are now trying to use this for jobs in folders (using the Cloudbee"s Folders plugin).

Integration is working OK, except that new jobs are always created in root of Jenkins.

For example, if I have https://jenkins.domain/job/MyFolder/job/MyJob, configured to look at the master branch of my Gitlab project, when I create a new branch from master (that I call "test"), the following is created : https://jenkins.domain/job/MyJob_test. Not in the right folder.

But, if I do a search in Jenkins for "MyJob", here is what I get : 
 - MyJob
 - MyJob_test
 - MyFolder MyJob
 - MyFolder/MyJob_test

The last link is not working. It seems to be related to the "/" added to it.

Am I missing something ?

### PR DESCRIPTION
**Pull request by pdudits**
Do not build accepted merge requests unless specified so in the configuration.

The combination of state and action upon approval is "updated" and "approved". Therefore
such combination cannot be excluded by using logical or.

Therefore the meaning of the arguments to MergeRequestHookTriggerHandlerImpl changed,
and tests were adjusted properly.

Fixes #633 .

### CODE REVIEW

**Comment by omehegan** [comment]
@pdudits can you clarify what issue this fixes? You reference #663 but that looks to be unrelated to what you are talking about here.

**Comment by chinhodado** [comment]
I believe he meant #633, not #663. Would be nice if this can be reviewed and merged quickly.

**Comment by pdudits** [comment]
Thanks @chinhodado, That's exactly what I meant, the numbers got somehow mixed up :)

**Comment by chinhodado** [comment]
@pdudits Is this commit based on the latest master? If not can you do a rebase? I want to test the build snapshot.

**Comment by pdudits** [comment]
There you go, @chinhodado

**Comment by chinhodado** [comment]
Thanks, I tested it and it works great.

**Comment by jakub-bochenski** [comment]
Tested this with Gitlab 10.4.3-ee and it works (both the enabled and disabled scenario)

**Review by jakub-bochenski — APPROVED** [review]

**Comment by jakub-bochenski** [comment]
@pdudits actually the title should be "Do not build approved merge requests ..."

Approving and accepting a merge request are different things in Gitlab.

**Comment by omehegan** [comment]
Thanks everyone for this contribution! I'll get it released ASAP.

**Comment by omehegan** [comment]
This was fixed/released in version 1.5.4 of the plugin, which should be available in the update center soon.

**Pull request merged**
