### PR TITLE
Clarify log line for not allowed branches

### PR DESCRIPTION
**Pull request by chinhodado**
### Before submitting a pull request, please make sure you read the instructions in the ["Contribution to the Plugin"](https://github.com/jenkinsci/gitlab-plugin/tree/master#contributing-to-the-plugin) section in the README.

*(if you read the above instructions, remove the paragraph and start describing the pull request)*

### CODE REVIEW

**Comment by omehegan** [comment]
This change makes the log look LESS clear to me. Can you explain why you feel this is an improvement?

**Comment by chinhodado** [comment]
With the original log I can't tell which branch is the source and which branch is the target, unless I look at the code.

**Comment by omehegan** [comment]
@chinhodado wow, I feel stupid - I read the diff exactly backwards! Yes your change is clearer :) Thanks.

**Comment by omehegan** [comment]
@chinhodado the change does not build locally or in the cloud Jenkins. Can you look into that?

**Comment by chinhodado** [comment]
Sorry I didn't notice, it should be good now

**Comment by omehegan** [comment]
Not sure what happened with the cloud build, but it works now when I build locally.

**Comment by omehegan** [comment]
Released in 1.5.11.

**Pull request merged**
