### PR TITLE
Configure Gitlab URL at job level

### PR DESCRIPTION
**Pull request by WonderCsabo**
Implements https://github.com/jenkinsci/gitlab-plugin/issues/121.

This is my first contribution to a Jenkins plugin, so please review carefully. Thanks!

### CODE REVIEW

**Comment by gregoire-jianda** [comment]
:+1:

**Comment by gregoire-jianda** [comment]
@WonderCsabo Would you happen to know what's this PR status ? Is there changes you've been asked to make, or is it just waiting for approval ? I would love to see this merged :)

**Comment by WonderCsabo** [comment]
@gbelorgey i did not get any response from the project maintainers about this PR unfortunately.

If you really need this feature, just clone the repo, merge my branch and build locally, then you can install  the hpi file easily from the Jenkins UI.

**Comment by gregoire-jianda** [comment]
Thanks @WonderCsabo, I'll try that way

**Comment by omehegan** [comment]
@WonderCsabo I'm catching up on PRs, sorry for the silence. Can you resolve merge conflicts? Then I can accept this.

**Comment by WonderCsabo** [comment]
Thanks for the feedback @omehegan !

I resolved the conflicts, but i still want to test it on our Jenkins instance. I will update the PR tomorrow.

**Comment by WonderCsabo** [comment]
I tested everything, it should be OK. @omehegan

**Comment by coder-hugo** [comment]
What's your use case for this change? Do you need a separate GitLab configuration for each of your jobs or do you have a few GitLab instances that have multiple repos for multiple jenkins jobs. A little visualisation of what I mean:
a)
- GitLab 1 -> Jenkins job 1
- GitLab 2 -> Jenkins job 2
- GitLab 3 -> Jenkins job 3
- ...

b)
- GitLab 1 -> Jenkins job 1, Jenkins job 2
- GitLab 2 -> Jenkins job 3, Jenkins job 4, Jenkins job 5
- ...

If b) is the case I'd prefere configuring mutliple GitLab instances in the global configuration and add a drop down selection at the job level. My intention for this is to keep the configuration as simple as possible. There are already a lot of checkboxes, input fields, radios for the trigger configuration (IMO already to much). This change will add again new inputs which will make the configuration even more complex. I assume there are only a few people that need to configure multiple GitLab instances. So I think we shouldn't make the configuration more complex than necessary for all the others using this plugin.

**Comment by WonderCsabo** [comment]
@coder-hugo yes, our use-case is _b)_, and that should be the case with multiple Gitlab instances.

You are right that it would be more convenient to just add these setting globally. However i do not know how it can be implemented. @mattiasb also [suggested](https://github.com/jenkinsci/gitlab-plugin/issues/121#issuecomment-148735005) we could store these info in the Credentials plugin, but i have even less clue for that one.

So if i get any help to implement this global dropdown, i would happily do it.

**Comment by coder-hugo** [comment]
I implemented a first draft for configuring multiple GitLab instances: [feature/multiple-gitlab-connections](https://github.com/coder-hugo/gitlab-plugin/tree/feature/multiple-gitlab-connections) 
If you like you can continue the work based on this branch otherwise I'll do this tomorrow.

**Comment by WonderCsabo** [comment]
@coder-hugo great! I will not be able to do work on this tomorrow, and anyway you seem more experienced than me, so please go ahead. :)

**Comment by WonderCsabo** [comment]
Closing in favor of #198 . @omehegan please review that PR instead!

**Pull request closed without merging**
