### PR TITLE
JENKINS-44517 Add a function to (re)set the Gitlab connections

### PR DESCRIPTION
**Pull request by roidelapluie**
Add a function to overwrite the Gitlab connections in the groovy
console.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by omehegan** [comment]
@roidelapluie what's the use case for this exactly?

**Comment by roidelapluie** [comment]
Setting gitlab connections from Groovy init.groovy.d hooks

**Comment by omehegan** [comment]
@roidelapluie I'm just trying to understand what you would use that for.

**Comment by roidelapluie** [comment]
init.groovy.d script

```
import jenkins.model.Jenkins;
import com.dabsquared.gitlabjenkins.connection.GitLabConnection
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.*
import org.jenkinsci.plugins.plaincredentials.impl.*
import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
import hudson.plugins.sshslaves.*
import org.apache.commons.fileupload.*
import org.apache.commons.fileupload.disk.*
import java.nio.file.Files
import com.dabsquared.gitlabjenkins.connection.GitLabApiTokenImpl
import hudson.util.Secret

// Workaround to use Yaml
def snakeYamlJar = new File("/var/lib/jenkins/snakeyaml-1.18.jar");
this.class.classLoader.addURL(snakeYamlJar.toURI().toURL());
def myYaml = Class.forName("org.yaml.snakeyaml.Yaml").newInstance();
gitlabConfigFile = new FileInputStream(new File("/var/lib/jenkins/secrets/gitlab.yaml"))
def gitlabConfig = myYaml.load(gitlabConfigFile)

def gitlabPlugin = Jenkins.instance.getDescriptor("com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig")


global_domain = Domain.global()
credentials_store =
  Jenkins.instance.getExtensionList(
    'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
  )[0].getStore()

def connections = new ArrayList<>();

gitlabConfig.each { it ->
    def gitlabCredentials = new GitLabApiTokenImpl(
      CredentialsScope.GLOBAL,
      it.name,
      "gitlab API key for #{it.url} - #{it.name}",
      new Secret(it.apiTokenId)
    )
    credentials_store.addCredentials(global_domain, gitlabCredentials)
    connections.add(new GitLabConnection(
        it.name,
        it.url,
        it.apiTokenId,
        it.ignoreCertificateErrors,
        it.connectionTimeout,
        it.readTimeout))
}

gitlabPlugin.setConnections(connections)


```

**Comment by roidelapluie** [comment]
@omehegan can we get this merged?

**Comment by roidelapluie** [comment]
ping @omehegan @evgeni

**Comment by omehegan** [comment]
Is the purpose of this so that you can bootstrap a new Jenkins server and have the GitLab connections set up automatically? That's what I was looking for when I asked what the use case is. I just want to understand how you see the feature being used.

**Comment by roidelapluie** [comment]
Yes that is the use case.

**Comment by roidelapluie** [comment]
Using a file in a docker volume to setup connections when starting jenkins in docker container

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.

**Pull request merged**
