### PR TITLE
WIP: Add support for "Draft" in MR title

### LINKED ISSUE #1194: "Draft" is not supported as a WIP indicator in MR title
### Background

When creating an MR, a user could add in "WIP" to their GitLab MR title and the MR would be indicated as "work in progress".

When the "WIP" indicator is removed it sends a Merge Request Hook and then a build would be started.

This function [1] checks that the "WIP" text was removed.

### Problem

GitLab added in a new indicator, "Draft", that is intended to replace "WIP". Both indicators are currently supported by GitLab but in [1], "Draft" is not supported.

Since "Draft" is not supported, a new build will not be started when it  is removed from the MR title.

### Solution
Modify the WIP function [1] to support "Draft" as described in the documentation [2].

I threw together a potential solution in #1195

[1] https://github.com/jenkinsci/gitlab-plugin/blob/gitlab-plugin-1.5.22/src/main/java/com/dabsquared/gitlabjenkins/trigger/handler/merge/MergeRequestHookTriggerHandlerImpl.java#L269
[2] https://docs.gitlab.com/13.12/ee/user/project/merge_requests/drafts.html#mark-merge-requests-as-drafts

### PR DESCRIPTION
**Pull request by NikolasKomonen**
Fixes: #1194

Signed-off-by: Nikolas Komonen <nkomonen@redhat.com>

### CODE REVIEW

**Review by jbliznak — APPROVED** [review]
Thanks for this, hopefully it will be merged soon

**Comment by omerjacobi** [comment]
Hi, can we merge this fix?, I really want to use this feature again

**Comment by BerSomBen** [comment]
Hi @NikolasKomonen,

what about this PR? its currently in DRAFT State, so its never going to be reviewed nor merged. 

would you remove the DRAFT state please? 

thanks in advance! 

looking forward to use it,

best,
bersomben

**Comment by omerjacobi** [comment]
@NikolasKomonen can you remove the draft?, I checked it and this works

**Comment by krisstern** [comment]
Hi @NikolasKomonen Would that be okay for me to open a new PR based on this work? This may be too old to merge?

**Comment by NikolasKomonen** [comment]
@krisstern Yup feel free to take it over. I won't have any time to work on this myself.

**Comment by krisstern** [comment]
Thanks @NikolasKomonen! I will start another PR to follow up on this shortly

**Comment by krisstern** [comment]
To be followed up at #1459.

**Pull request closed without merging**
