### PR TITLE
Use BRANCH_NAME in environment as fallback

### LINKED ISSUE #1010: gitlabCommitStatus pushing status to wrong branch
### Context
- **Gitlab plugin version**: 1.5.13
- **Gitlab version**: 12.5.3-ee
- **Jenkins version**: 2.190.1` **Job type**: Multi branch Pipeline

### Problem description
When we are creating new branch (without pushing commits) - for example TestBranch from Develop it triggers build on TestBranch. But gitlabCommitStatus is reporting to Develop branch, leaving TestBranch without status.

Here is my test pipeline
```
properties([gitLabConnection('MyGitLabConnection')])
node('linux') {
  stage('Test') {
    gitlabCommitStatus('Test') {
      println('Test')
    }
  }
}
```

### PR DESCRIPTION
**Pull request by martinnemec3**
Using ff only merging strategy in gitlab results in having same commit on a feature branch and on the main branch (there it appears after the merging is done). This PR tries to fix the situation when jenkins multibranch pipeline job is used to build both the feature branch and main branch. The problem is that status update request does not contain the "ref" parameter needed to set the  status for branch correctly.

Fixes https://github.com/jenkinsci/gitlab-plugin/issues/1010.

### CODE REVIEW

**Review by basil — COMMENTED** [review]
> This PR tries to fix the situation

Does this PR try to fix the situation, or do you know for sure that it fixes the situation? That is, are you running this PR in production and have you verified this PR fixes the problem? I am more of an interim maintainer than a maintainer, I don't use GitLab, and I have no way of testing this change. I would only feel comfortable merging and releasing this PR if you have tested it on a production Jenkins server.

**Comment by martinnemec3** [comment]
> Does this PR try to fix the situation, or do you know for sure that it fixes the situation?

It actually fixes the situation.

> That is, are you running this PR in production and have you verified this PR fixes the problem?

The problem is not hard to reproduce so I just tested the fix in my local (docker) test environment (set up by following https://github.com/jenkinsci/gitlab-plugin/blob/master/src/docker/README.md).
I do not run the code anywhere in production.

**Comment by basil** [comment]
Any chance you could download the incremental build from https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/gitlab-plugin/1.5.33-rc1406.50cf09d3a_6fd/ and do a functional test on a production server? For instructions on how to install a custom plugin build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Comment by basil** [comment]
Sorry to leave you halfway through review, but I recently removed myself as the maintainer of this plugin in https://github.com/jenkins-infra/repository-permissions-updater/pull/2605, so I will not be able to merge this PR. You can consider [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) to merge and release the PR. The "[Contributing to Open Source](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.hvd0nm6pz5o4)" workshop from DevOps World 2021 is a useful starting point for new maintainers. That document includes links to a [five part video series](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.oz0bxvhyvna5) that illustrates many of the steps. If the plugin is crucial to your work, you may want to ask your employer to support your work efforts by allowing you to adopt the plugin.

**Comment by krisstern** [comment]
@martinnemec3 Thanks for the PR! The solution looks intuitive enough for me.

**Comment by krisstern** [comment]
An ideal situation is if someone can test this out on a production server...

**Review by krisstern — APPROVED** [review]

**Comment by krisstern** [comment]
Thanks @martinnemec3!

**Pull request merged**
