### PR TITLE
[GSoC Milestone 2] Migrating WebHook Draft

### PR DESCRIPTION
**Pull request by harsh-ps-2003**
Migrating the old manual Webhook implementation to GitLab4J-API event-based Webhook.
This PR is based on Milestone 1 code.
CauseData has not been affected yet.
Tests not adapted yet.

**NOT **WORKING****

This draft pr is to collaborate on fixing issues.

### CODE REVIEW

**Comment by harsh-ps-2003** [comment]
This PR is non-functional currently, but I still made the Draft PR so that the approach towards the migration could be verified in code. 
The compilation errors in CI are due to compilation errors in tests.

**Comment by harsh-ps-2003** [comment]
The PR is now functioning interactively. Tests for it are WIP.
@basil kindly take a look please.

**Comment by krisstern** [comment]
> The PR is now functioning interactively. Tests for it are WIP.

Noted 👍🏼

**Comment by MarkEWaite** [comment]
Replaced by 

* #1553

**Pull request closed without merging**
