### PR TITLE
Add all trigger fields to the documentation 

### PR DESCRIPTION
**Pull request by AniketNS**
I have added the missing trigger fields to the `gitLabConnection` pipeline trigger and `gitLabBuilds` for issue #1477

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@AniketNS thanks for the pull request.  In future pull requests, please submit them from a branch that is **not the primary branch** of the repository.  In the case of this repository, the primary branch is named "master".  You submitted this pull request from the master branch of your local fork.  That meant I had to take some extra steps in order to push the white space correction in 5c4aad320654b1e9e36aa90c1235365021d09fec

The pull request checklist does not include that item, but should, since it is a preferred practice in most open source projects and a preferred practice in the Jenkins project.

I've proposed a pull request to adjust the pull request template in this repository so that it matches with other Jenkins plugins..  That pull request is:

* #1604

No need to make any change to this pull request.  Using the master branch as the basis for this pull request is only a minor inconvenience.  I only mention it in this review comment for future pull requests.  Don't disrupt the review process of this pull request by attempting to change the base branch used for the changes.

**Comment by AniketNS** [comment]
Sure @MarkEWaite, actually I did create a different branch named `aniket` but when I pushed code from that branch, I didn't see the `compare and pull request` on GitHub. I don't know why this happened. That's why once again I pushed code from the master branch. You can see the commits.

**Comment by MarkEWaite** [comment]
The [GitHub pull request documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) provides a very good description of the process.  

If you prefer it in a video format specifically for Jenkins, refer to the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/).

**Comment by AniketNS** [comment]
> The [GitHub pull request documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) provides a very good description of the process.
> 
> If you prefer it in a video format specifically for Jenkins, refer to the ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/).

Ok, Thanks

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Pull request merged**
