### PR TITLE
Add missing gitlab hook event headers

### PR DESCRIPTION
**Pull request by Balint134**
PR for https://github.com/jenkinsci/gitlab-plugin/issues/608

### CODE REVIEW

**Comment by omehegan** [comment]
Thanks for the bug report and this PR. But if I merge this as-is, presumably it's going to break anyone using an earlier version of GitLab. I need some feedback from the GitLab folks about what happened here. I've requested that on the Issue page.

**Comment by adjika** [comment]
@omehegan I can't speak for the PR since I don't have a GitLab 9.5.0 at hand to verify the issue right now, but could you clarify why the PR breaks older versions? From my, admittedly limited, understanding of the plugin it should still work with older GitLab versions since he just added fallthrough cases for the new x-gitlab-events, so I feel like I'm missing something here.

**Comment by Balint134** [comment]
@omehegan It should be backward compatible, as it is only extending the cases with fall-through options. Yeah feedback would be awesome from Gitlab because I can not find any documentation related to these changes, all I can see that the "Test webhook" fails thus of this Header change.

**Comment by Argelbargel** [comment]
@omehegan: as the header X-Gitlab-Event is only used by gitlab-plugin in the method ActionResolver#onPost which @SwankyPantie has changed and the header is not passed along or processed any further, this should indeed not break compatiblity.

**Comment by omehegan** [comment]
Oh, I'm sorry, I misread the diff; you're not removing the old entries, just adding these additional ones. I get it now.

**Comment by omehegan** [comment]
@SwankyPantie can you resolve merge conflicts?

**Comment by Balint134** [comment]
@omehegan Sure, done

**Comment by omehegan** [comment]
This appears to be a bug that was introduced in GitLab. For more context, please see the comments in the #608 issue. I am leaning towards not merging this, and letting GitLab fix it on their side, because this only affects the Test Hook functionality.

**Comment by omehegan** [comment]
Bug was fixed on GitLab side, see #608.

**Pull request closed without merging**
