### PR TITLE
Trigger build when merge request has been merged or closed

### PR DESCRIPTION
**Pull request by m9abbas**
Hello, the main of this pull request is to be able to trigger builds when a merge request has been accepted or closed (Please see #390 ).

### CODE REVIEW

**Comment by omehegan** [comment]
Nice PR, thank you! And it even has some tests :)

@colourmeamused @trance1st can either or both of you review this?

**Comment by mreichel** [comment]
The PR looks fine to me. Thanks! In my Jenkins the new checkboxes "forget" their values sometimes, though. I can't see anything wrong in the code (I guess it is a local problem), but maybe you can check this in your Jenkins @mabbas85?

**Comment by omehegan** [comment]
Configuration loss is, in my experience, NOT usually a local problem. There can be issues where the config is not saved to disk properly. I think this is worth investigating before we release this.

**Comment by m9abbas** [comment]
@mreichel, @omehegan  Thanks for accepting the PR! I am encountering the same problem in my local jenkins. I will investigate why it is happening.

**Comment by m9abbas** [comment]
I think i understood why it is happening. It was missing the `Getter` methods for the 2 fields i added in class `GitLabPushTrigger`. By adding these 2 methods, the problem seems to disappear. I will create a new PR that adds these 2 methods. Thanks for reporting this problem!

**Comment by omehegan** [comment]
@mabbas85 well done :)

**Comment by omehegan** [comment]
This was released today in version 1.4.6 of the plugin.

**Pull request merged**
