### PR TITLE
Reset stream when logging debug information

### LINKED ISSUE #1196: RESTEASY003765 after update to 1.5.23
After Update to 1.5.23 I got on two of three machines following errors:
In log the user response is shown but then the error occurs. Downgrade it again ant it works again

Client error: RESTEASY003765: Response is closed.

```
java.lang.IllegalStateException: RESTEASY003765: Response is closed.
     at 
org.jboss.resteasy.specimpl.AbstractBuiltResponse.abortIfClosed(AbstractBuiltResponse.java:308)
     at 
org.jboss.resteasy.client.jaxrs.internal.ClientResponse.abortIfClosed(ClientResponse.java:294)
     at 
org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:60)
     at 
org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:256)
     at 
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:144)
Caused: javax.ws.rs.client.ResponseProcessingException
     at 
org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:180)
     at 
org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
     at 
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
     at 
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
     at 
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.$Proxy125.getCurrentUser(Unknown 
Source)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.ResteasyGitLabClient.getCurrentUser(ResteasyGitLabClient.java:115)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetect(AutodetectingGitLabClient.java:317)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.autodetectOrDie(AutodetectingGitLabClient.java:305)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.delegate(AutodetectingGitLabClient.java:298)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.access$200(AutodetectingGitLabClient.java:14)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.execute(AutodetectingGitLabClient.java:335)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient$GitLabOperation.access$100(AutodetectingGitLabClient.java:332)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.execute(AutodetectingGitLabClient.java:328)
     at 
com.dabsquared.gitlabjenkins.gitlab.api.impl.AutodetectingGitLabClient.getCommit(AutodetectingGitLabClient.java:132)
     at 
com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:121)
     at 
com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:83)
     at 
com.dabsquared.gitlabjenkins.workflow.GitLabCommitStatusStep$GitLabCommitStatusStepExecution$1.onStart(GitLabCommitStatusStep.java:94)
     at 
org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.launch(CpsBodyExecution.java:135)
     at 
org.jenkinsci.plugins.workflow.cps.CpsBodyInvoker.launch(CpsBodyInvoker.java:187)
```

### PR DESCRIPTION
**Pull request by basil**
Fixes #1196

### CODE REVIEW

**Comment by basil** [comment]
Incremental build 1.5.24-rc1310.7f9db50e763b is available for testing. The incremental build is available from: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/gitlab-plugin/1.5.24-rc1310.7f9db50e763b/

@MCMicS Can you please test the incremental build and confirm the issue is resolved? For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Comment by MCMicS** [comment]
I try it tomorrow on one of my machine

**Comment by MCMicS** [comment]
@basil the incremental build show no error if loglevelis set

So it seems to fixed

**Review by MCMicS — APPROVED** [review]

**Comment by basil** [comment]
Released in [1.5.24](https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.5.24).

**Pull request merged**
