### PR TITLE
If BlueOcean is installed, build URL does not point to BlueOcean

### LINKED ISSUE #518: If BlueOcean is installed, build URL does not point to BlueOcean
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.4.3
- **Jenkins version**: 2.45
- **Job type**:  Multibranch Pipeline
- **BlueOcean version**: 1.0.0-b24	

### Problem description

When I visit the build link in Gitlab:
screen shot 2017-03-03 at 2 46 28 pm

it points to the classic Jenkins build URL:
screen shot 2017-03-03 at 2 48 45 pm

instead of opening the link in BlueOcean:
screen shot 2017-03-03 at 2 50 47 pm

### PR DESCRIPTION
**Pull request by i386**
Fixes #518.
@omehegan @jkdeveyra this should fix the issue with pointing to Blue Ocean as mentioned in #518

### CODE REVIEW

**Comment by omehegan** [comment]
Nice! Thanks James! Tests failing though...

**Comment by i386** [comment]
@omehegan the URLs are slightly different (we have an action that redirects you to classic or Blue Ocean) so those tests will need to be updated. Should be simple enough to do but I won't have time this week.

**Comment by omehegan** [comment]
Any chance you can fix up these tests?

**Comment by i386** [comment]
@omehegan sorry - I'm in launch mode and don't have time to code for at least another two weeks.

**Comment by ohartl** [comment]
@i386 Would realy like to use this. Are you able to complete this any time soon? Or should I try helping you out?

**Comment by i386** [comment]
@omehegan  I am not going to be able to get to this. Display URL plugin is pretty simple - have a look how its used in bitbucket

**Comment by omehegan** [comment]
@ohartl if you can provide any help with this, that would be great. Ironically, I don't have any Java skills :-/

**Comment by omehegan** [comment]
@Argelbargel @mreichel would either of you be interested in cleaning this up so it can be merged? I think getting better Blue Ocean support in the plugin would be a win and allegedly there is not much work needed to complete this.

**Comment by Argelbargel** [comment]
I'll try to look into it this week...

**Comment by Argelbargel** [comment]
As i'm not using blue ocean currently i'm not able to check whether the changes made by@i386's actually work, but the unit-tests and the [integration-tests](https://travis-ci.org/Argelbargel/gitlab-plugin/builds/302002395) are ok now ;-)

**Comment by omehegan** [comment]
@Argelbargel thanks! I will try to test this using the Docker test env.

**Comment by omehegan** [comment]
It seems to work! With Blue Ocean installed, links to builds from a GitLab MR take you to the BO UI. If it is not installed, the old-style build page loads. Thanks @i386 and @Argelbargel!

**Comment by i386** [comment]
Glad it worked out!

**Comment by omehegan** [comment]
This has just been released in plugin version 1.5.2. It will be in the update center within a few hours.

**Pull request merged**
