### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by dreef3**
Hopefully this is useful, I don't have that much experience with Jenkins plugins.
- Added base class for requests `GitlabRequest`
- Added base class for causes `GitlabCause`
- Many classes moved to separate files to improve readability
- Added settings to customize messages that Jenkins posts on Gitlab
- Fixed commit status, added handling for pending, aborted status
- Bumped versions of dependencies & jenkins plugin

Still work in progress, tested only with Gitlab 8.1.3.

### CODE REVIEW

**Comment by omehegan** [comment]
@dreef3 is this still a work in progress?

**Comment by dreef3** [comment]
@omehegan unfortunately yes. I had stuck on projects at work and didn't had time to finish it. Though it mostly works.

I'll try to finish it next week.

**Comment by markus-mnm** [comment]
I 'd might make it easier on you and any reviewer to split out some parts of this pull request into smaller junks.

**Comment by dreef3** [comment]
- Rebased on top of latest master.
- Fixed issues, tested with GitLab 8.2.x
- Reverted most of changes in pom.xml so tests should pass.

@markus-mnm, you're absolutely right it's hard to impossible to review current PR thoroughly. I can split this into multiple PRs but I'll need to base each next PR on the previous for that, is it ok?

**Comment by dreef3** [comment]
Also I'm going to install the plugin into Jenkins at work so PR should get more real-world testing next week.

**Comment by omehegan** [comment]
@dreef3 did you want to do any more work on this, or organize it differently? I've introduced conflicts by merging other requests.

**Comment by omehegan** [comment]
We are planning a more comprehensive refactor of the plugin's code. So, with thanks for your work on this, I'm going to close in favor of the upcoming revisions.

**Pull request closed without merging**
