### PR TITLE
Merge from master

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Merge from master branch

It is easier to manage a long-lived branch that is a descendant of another branch by regularly using `git merge` from the upstream branch. This pull request merges the master branch and reduces the differences between this branch and the master branch to only be in the Jenkinsfile.

- Add META-INF/ to .gitignore (#1479)
- Use surefire test configuration from master branch
- Add TODO explaining why tests are disabled

Long term, we'll let this be handled by https://github.com/jenkinsci/gitlab-plugin/actions/workflows/sync-project-branch.yml .  That action is currently failing and I don't understand the failure message well enough to fix it.

### CODE REVIEW

**Comment by krisstern** [comment]
@MarkEWaite I think maybe we can do `git pull origin master --allow-unrelated-histories` instead.

**Comment by krisstern** [comment]
Also for `fetch` we could do `git fetch origin --unshallow`

**Comment by MarkEWaite** [comment]
> Also for `fetch` we could do `git fetch origin --unshallow`

Thanks for detecting that.  If the working git repository is being populated with a shallow fetch or a shallow clone, then that would explain the message about unrelated histories.  Can you submit the pull request to update the GitHub action definition?

**Comment by krisstern** [comment]
Sure, I can do that

**Pull request closed without merging**
