### PR TITLE
#723 Build on successful pipeline events

### PR DESCRIPTION
**Pull request by mreichel**
Fix for #723

### CODE REVIEW

**Comment by mreichel** [comment]
Unfortunately I don't have a proper test environment anymore. The PR fixes the issue with not keeping the property, but I can't test if the other problem still exists.

**Comment by omehegan** [comment]
Thanks @mreichel :)

**Comment by omehegan** [comment]
This was just released in version 1.5.5 of the plugin. It should be available in the update center soon.

**Comment by kuzaxak** [comment]
Try to use it. I successfully setup hook with event "Pipeline Events" and in Jenkins make config for pipeline like that: http://take.ms/2tocF

In log I haven't any messages about it. Could you help me please? 
@mreichel 

Version of plugin: 1.5.5
Gitlab: 10.7.3

**Comment by mreichel** [comment]
Unfortunately, the bug is not fixed yet and I am pretty much out, since I don't use the Jenkins/Gitlab combination any longer.

**Comment by omehegan** [comment]
@kuzaxak please follow issue #723. If you see nothing at all in your logs, you have configured the plugin incorrectly.

**Pull request merged**
