### PR TITLE
Send GitLab messages on unstable builds as well as failed ones

### PR DESCRIPTION
**Pull request by sauliusgrigaitis**
I'm submitting this small fix for #452. It's not full configurable feature as described in #452, but it does the job without allowing to configure details.

### CODE REVIEW

**Comment by omehegan** [comment]
I think we should expand on this to make it configurable before we merge it.

**Comment by sauliusgrigaitis** [comment]
Well, question is does anybody really need that flexible configuration. I personally think that those people who use Unstable status in their builds would also like to get notifications just like they get for Failed builds. Those who doesn't use Unstable status at all will even not notice this merge request.

**Comment by omehegan** [comment]
@sauliusgrigaitis sorry for the long delay on this. I wanted to merge this today, but tests are failing. Can you try rebasing with master, and let's see if the tests pass now?

**Comment by sauliusgrigaitis** [comment]
@omehegan done!

**Comment by omehegan** [comment]
This was released today in version 1.4.8 of the plugin.

**Pull request merged**
