### PR TITLE
feat: GitLab OAuth2 provider as Jenkins SecurityRealm

### PR DESCRIPTION
**Pull request by bufferoverflow**
Signed-off-by: Roger Meier r.meier@siemens.com
Reviewed-by: Fabio Huser fabio.huser@siemens.com
Tested-by: Rudolf Honegger rudolf.honegger@siemens.com

### CODE REVIEW

**Comment by omorillo** [comment]
Hello @bufferoverflow, Thank you for your pull request. I will review the code and test the feature and if everything works fine I will merge it.

**Comment by omehegan** [comment]
@bufferoverflow can you explain what this feature enables? When you refer to the Jenkins SecurityRealm, it makes me think this allows you to authorize access to Jenkins based on accounts in GitLab. If that's correct, I'm not sure it makes sense to include this in our plugin, which is currently just a build trigger interface. 

Is there any reason why the generic Jenkins oauth plugin can't be used to authorize against a GitLab system?

I apologize if I've just misunderstood the intent of this change.

**Comment by omorillo** [comment]
No, I think you're right @omehegan. It seems to be rather some Jenkins core functionality. Me too was wondering about this sort of feature for our gitlab-plugin and wanted to look what is the functionality about to check whether I am wrong with my understanding. But I hope @bufferoverflow can bring some clarification to this question.

**Comment by bufferoverflow** [comment]
Yes, this extension allows Authorization of Jenkins users via GitLab. 

OAuth is not that generic as we would like to have it, each OAuth service provider has little different semantics, there are a lot of different OAuth plugins around e.g. Google, GitHub.

We decided to create a pull request here, because the plugin name is generic **gitlab-plugin** and we prefer to have one plugin with GitLab functionality instead of adding an additional plugin. I have the feeling there might be other synergies in the future.

**Comment by omorillo** [comment]
@bufferoverflow The name of the plugin is pretty generic, this for sure. Still this feature deviates completely from the idea of the gitlab-plugin which is to trigger jobs on push to a certain branch or on submission of a merge request. I don't think this feature fits to this plugin.

**Comment by omorillo** [comment]
Do you see it similar, @omehegan?

**Comment by bufferoverflow** [comment]
I would appreciate I you could give it a try, it does not influence any functionality of your plugin. It's just an addon and I believe it is a worth to have addon for GitLab users that are searching for GitLab plugins.

**Comment by omehegan** [comment]
Let me take a look and think about it, I was involved with some work on the Jenkins OAuth plugins a year or two ago. At a minimum I think people would not expect to find this auth functionality inside the GitLab plugin, so if we did adopt it we would need to change the way we present it.

**Comment by bufferoverflow** [comment]
And of course, we are using your plugin already.

**Comment by omehegan** [comment]
Upon discussion amongst ourselves (the maintainer team) and with core Jenkins developers, we agree that the best practice would be for this feature to be implemented as its own plugin. This pattern is used in various similar cases, such as the separate GitHub and GitHub auth plugins. As such, while we really appreciate that you submitted this feature, we think this is not the best place for it. If you need help getting this refactored to be its own plugin, let us know and we can point you to some resources for that. Thank you!

**Pull request closed without merging**
