### PR TITLE
fix: #636 fix Jenkins won't trigger a build of merge commit on merged…

### PR DESCRIPTION
**Pull request by yili1992**
This commit fixes issue #636, #1023

### CODE REVIEW

**Review by markjacksonfishing — CHANGES_REQUESTED** [review]
Auto build failure in ci failed.

**Comment by zbynek** [comment]
Actually all the PR builds for the plugin are failing because the POM in master is invalid. Maybe better to fix that in another PR https://github.com/jenkinsci/gitlab-plugin/pull/1102

**Comment by pyssling** [comment]
@yili1992 could you try rebasing this?

**Comment by yili1992** [comment]
> @yili1992 could you try rebasing this?

thanks, I found the POM has been fixed , I will rebase

**Comment by yili1992** [comment]
> Auto build failure in ci failed.

@markyjackson-taulia  Hi markyjackson-taulia , at present, ci successed , please review, thanks

**Comment by dskrvk** [comment]
Looks like this was made it into version 1.5.21, but that still doesn't seem to have been published to the Jenkins plugins directory: https://plugins.jenkins.io/gitlab-plugin/#releases

**Comment by basil** [comment]
@dskrvk @pyssling @yili1992 The changes in this PR will be released in the forthcoming 1.5.22 release. Incremental build 1.5.22-rc1276.9f26cf564af5 is available for testing. Please test the incremental build and report any regressions from 1.5.20.

The incremental build `.hpi` file can be downloaded from here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/gitlab-plugin/1.5.22-rc1276.9f26cf564af5/

For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Pull request merged**
