### PR TITLE
Fix acceptMergeRequestOnSuccess configuration

### LINKED ISSUE #120: Checkbox acceptMergeRequestOnSuccess set to "checked" always
When I open Jenkins Job Configure page, acceptMergeRequestOnSuccess checkbox set to "checked" state always even if there was unchecked earlier and option <b>acceptMergeRequestOnSuccess</b> in file Jobname/config.xml set to <b>false</b> too.

### PR DESCRIPTION
**Pull request by jsyrjala**
Fixes #120 and set default for acceptMergeRequestOnSuccess to false.

### CODE REVIEW

**Comment by jsyrjala** [comment]
I tested the PR with GitLab 6.9.2 and Jenkins ver. 1.617. Works fine.

**Comment by nerzhul** [comment]
Please merge this before next release, this bug is very annoying when you review a pull requests to have the PR merged

**Comment by omehegan** [comment]
I'm reviewing this now. I've seen this type of "change the default" fix in other areas of Jenkins, and one thing to watch out for is that it will only be different for jobs that enable the trigger after this update. Those that already have it enabled will need to manually change the setting and save.

**Comment by omehegan** [comment]
@jsyrjala thanks! I'm hoping to do a release in the next week or so.

**Comment by nerzhul** [comment]
Thanks !

**Comment by vytis** [comment]
Any news when this could get released? This bug broke our code review flow completely, so testing of merge requests is disabled for now...

**Comment by DiegoCoronel** [comment]
> Any news when this could get released? This bug broke our code review flow completely, so testing of merge requests is disabled for now...

I need this fix too

**Comment by omehegan** [comment]
I will release this today.

**Pull request merged**
