### PR TITLE
Reverted changes

### PR DESCRIPTION
**Pull request by impact-maker**
Description
Reverted back the changes in the build to fix issue #1309

### CODE REVIEW

**Review by daniel-beck — CHANGES_REQUESTED** [review]
Please do not introduce security vulnerabilities by reverting previous security fixes.

**Comment by impact-maker** [comment]
> Please do not introduce security vulnerabilities by reverting previous security fixes.

Thanks for replying. Since I am a new contributer, could you help by guiding on how to reproduce issue #1309 and any insights to understand the issue better would be appreciated. Thank you

**Comment by daniel-beck** [comment]
> how to reproduce issue

Unsure what you mean. If you're referring to [SECURITY-2316](https://www.jenkins.io/security/advisory/2022-06-30/#SECURITY-2316), put HTML in the payload of the webhook (which fields are included depends on the type of webhook) and see it rendered here.

**Comment by krisstern** [comment]
Hi @daniel-beck I think there must have been some confusion. I looked and it seems #1309 has already been address previously in https://github.com/jenkinsci/gitlab-plugin/commit/24e9a99d8151b5345109ef12cddc1ab323baa4ee. Could you please confirm so that I can close both this PR and the corresponding issue?

**Comment by krisstern** [comment]
@impact-maker I have just checked the issue was in fact a notice so the best we can do is to report it as completed instead of reverting to a former state to expose the previous vulnerabilities. But thanks for your code contribution!

**Comment by daniel-beck** [comment]
> Hi @daniel-beck I think there must have been some confusion. I looked and it seems #1309 has already been address previously in [24e9a99](https://github.com/jenkinsci/gitlab-plugin/commit/24e9a99d8151b5345109ef12cddc1ab323baa4ee). Could you please confirm so that I can close both this PR and the corresponding issue?

I filed #1309 after I published https://github.com/jenkinsci/gitlab-plugin/commit/24e9a99d8151b5345109ef12cddc1ab323baa4ee, so no, it's not addressed. The issue is asking to restore the previous detailed build causes, but in a safe manner (i.e., not just undoing the security fix, as this PR did).

**Pull request closed without merging**
