### PR TITLE
Fix/merge request hooks behavior

### LINKED ISSUE #705: The "Never" option for "Rebuild open Merge Requests" does not prevent a build
## Issue
When setting up the Build Triggers for our Jenkins jobs, we use:
Build when a change is pushed to GitLab = checked
Opened Merge Request Events = checked
Rebuild open Merge Requests = Never

The behavior with gitlab-plugin v1.1.32 was that when an open and previously failed merge request had a subsequent push, the build did NOT get triggered.  When we upgraded to 1.4.5 this was no longer the case.  A rebuild occurred even with the option set to Never.  We recently upgraded to v1.5.1 and it is still triggering the rebuild.  The documentation on the home page does not describe expected behavior for this configuration, but intuitively this seems broken to me.

### Context
- **Gitlab plugin version**: 1.5.1
- **Gitlab version**: 10.2.4-ee
- **Jenkins version**: 2.59
- **Job type**: Maven project

### Logs & Traces

**Following is the Discussion in Gitlab:**
Dev Builder @devbld commented 24 minutes ago
Developer

❎ Jenkins Build FAILURE

Results available at: Jenkins [diqfe-parent #77]

 
Dev Builder @devbld commented 24 minutes ago
Developer

👎

Bradt Timothy P @bradttp added 1 commit 22 minutes ago 
1b79cca6 - DOS-1016: Test if the new gitlab-plugin fixes the problem with "Never" rebuild…
Compare with previous version

 
Dev Builder @devbld commented 21 minutes ago
Developer

✅ Jenkins Build SUCCESS

Results available at: Jenkins [diqfe-parent #78]

 
Dev Builder @devbld commented 21 minutes ago
Developer

👍

Dev Builder @devbld merged 21 minutes ago 

**These are the 2 Jenkins log entries showing the merge request triggered both builds:**
14:52:37 Triggered by <a href="" target="_blank">GitLab Merge Request #44</a>: fe/dev_test_gitlab_plugin => master

14:54:52 Triggered by <a href="" target="_blank">GitLab Merge Request #44</a>: fe/dev_test_gitlab_plugin => master

### Problem description
With the above configuration...
1) Push a change that intentionally breaks a build.
2) Create a merge request and verify the build fails and merge request remains open.
3) Revert the change and push (i.e. fix broken build).
4) Expect it to never rebuild, but a new build is triggered immediately/automatically.

### PR DESCRIPTION
**Pull request by jbpratt**
Fixes #705.

This merge request builds onto https://github.com/jenkinsci/gitlab-plugin/pull/869 fixing the remaining test that was failing.

Thank you to @Osmyslitelny for the original fix!

### CODE REVIEW

**Comment by jbpratt** [comment]
Hi @markyjackson-taulia (sorry for the 2 year late ping!!) and @basil (as the most active contributor currently), I've fixed the CI from https://github.com/jenkinsci/gitlab-plugin/pull/869#issuecomment-608641423 . Would you be able to take a look if you have the time? 

edit: never mind, sorry for the tags, I see there are no active maintainers anymore :crying_cat_face:

**Comment by jbpratt** [comment]
Hi @omehegan ! Would you be able to take a look at this? Sorry, just trying to get this resolved.

**Comment by basil** [comment]
@jbpratt I am no longer maintaining this plugin and no longer have permissions to release it. If the changes from this PR work, you can consider [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) to merge and release the PR. The "[Contributing to Open Source](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.hvd0nm6pz5o4)" workshop from DevOps World 2021 is a useful starting point for new maintainers. That document includes links to a [five part video series](https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#heading=h.oz0bxvhyvna5) that illustrates many of the steps. If the plugin is crucial to your work, you may want to ask your employer to support your work efforts by allowing you to adopt the plugin.

**Review by krisstern — APPROVED** [review]
Looks good! Thanks @jbpratt for the contribution

**Pull request merged**
