### PR TITLE
Three tests are flaky

### PR DESCRIPTION
**Pull request by basil**
https://github.com/jenkinsci/bom/pull/2362/checks?check_run_id=15956053621 failed due to test flakiness.

### CODE REVIEW

**Comment by basil** [comment]
Caused by https://github.com/jenkinsci/jenkins-test-harness/pull/198.

**Review by krisstern — APPROVED** [review]
LGTM

**Comment by basil** [comment]
Can this please be released to decrease flaky test failures in `jenkinsci/bom`?

**Comment by krisstern** [comment]
Sure, let me cut a new release within the next day or two.

**Comment by krisstern** [comment]
Done cutting a new release: https://github.com/jenkinsci/gitlab-plugin/releases/tag/gitlab-plugin-1.7.16

**Comment by basil** [comment]
Thank you!

**Comment by krisstern** [comment]
You are welcome!

**Pull request merged**
