### PR TITLE
Provide merge request labels as environment variables

### LINKED ISSUE #900: Accessing labels in build
## Issue

Note: MR #646 would've helped me here, but it was never merged.

### Context
- **Gitlab plugin version**: 1.5.11
- **Gitlab version**: 11.7.5
- **Jenkins version**: 2.89.4
- **Job type**: Pipeline

### Logs & Traces

Output from `echo sh(returnStdout: true, script: 'env')` in build (only showing variables related to this plugin):

```gitlabMergeRequestTargetProjectId=56
gitlabSourceRepoURL=git@git.example.com:group/project.git
gitlabTargetRepoHttpUrl=https://git.example.com/group/project.git
gitlabMergedByUser=anton-johansson
gitlabTargetRepoSshUrl=git@git.example.com:group/project.git
gitlabTargetBranch=master
gitlabMergeRequestIid=1023
gitlabSourceRepoHttpUrl=https://git.example.com/group/project.git
gitlabMergeRequestState=opened
gitlabMergeRequestTitle=Test
gitlabMergeRequestLastCommit=d4f4b002445261f691ec45bffc4dc81534e50f0e
gitlabSourceRepoSshUrl=git@git.example.com:group/project.git
gitlabTargetRepoName=Project
gitlabTargetNamespace=Group
gitlabSourceRepoHomepage=https://git.example.com/group/project
gitlabBranch=anton-test
gitlabSourceBranch=anton-test
gitlabUserEmail=antoon.johansson@gmail.com
gitlabMergeRequestId=5618
gitlabActionType=MERGE
gitlabSourceRepoName=Project
gitlabSourceNamespace=Group
gitlabUserName=Anton Johansson
```

### Problem description

I would like to access MR labels so I can perform various logic depending on them. My main idea here is to automatically deploy to my Kubernetes cluster if a certian label is set. I want this because I don't want to push Docker images to our repository for every commit in every MR. Only the ones that are relevant to deploy.

This also means that I want to be able to trigger a build by only adding a label (this specific label, if possible). Issue #871 states that this is already happening, but it isn't for me.

### PR DESCRIPTION
**Pull request by anton-johansson**
Closes #900
Also see #646

Example pipeline:
```
pipeline {
    agent any
    triggers {
        gitlab(
            triggerOnPush: true,
            triggerOnMergeRequest: true,
            triggerOpenMergeRequestOnPush: "source",
            triggerOnNoteRequest: true,
            branchFilterType: "All",
            skipWorkInProgressMergeRequest: false)
    }
    stages {
        stage('Prepare') {
            steps {
                echo sh(returnStdout: true, script: 'env')
            }
        }
    }
}
```

Output:
```
[Pipeline] sh
+ env
[Pipeline] echo
gitlabMergeRequestTargetProjectId=1
gitlabSourceRepoURL=ssh://git@localhost:10022/root/anton.git
JENKINS_HOME=/var/jenkins_home
gitlabTargetRepoHttpUrl=http://localhost:10080/root/anton.git
JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
gitlabMergedByUser=root
RUN_CHANGES_DISPLAY_URL=http://localhost:8080/job/anton/5/display/redirect?page=changes
HOSTNAME=4ea3e1ce3cbc
gitlabTargetRepoSshUrl=ssh://git@localhost:10022/root/anton.git
SHLVL=0
NODE_LABELS=master
HUDSON_URL=http://localhost:8080/
HOME=/var/jenkins_home
BUILD_URL=http://localhost:8080/job/anton/5/
HUDSON_COOKIE=85dd3aca-ba51-4ed6-91ce-ffad4cb29895
gitlabTargetBranch=master
JENKINS_SERVER_COOKIE=durable-6b17982e7e0d911a16d9ced57c7aafff
gitlabMergeRequestIid=1
JENKINS_UC=https://updates.jenkins.io
gitlabSourceRepoHttpUrl=http://localhost:10080/root/anton.git
gitlabMergeRequestState=opened
WORKSPACE=/var/jenkins_home/workspace/anton
gitlabMergeRequestTitle=Update README.md
JAVA_VERSION=8u151
gitlabMergeRequestLastCommit=d0b6cdced0adb9808a27787b8cc5d58459170840
NODE_NAME=master
gitlabSourceRepoSshUrl=ssh://git@localhost:10022/root/anton.git
gitlabTargetRepoName=anton
gitlabTargetNamespace=root
gitlabMergeRequestLabels=deploy,bug
STAGE_NAME=Prepare
CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
gitlabSourceRepoHomepage=http://localhost:10080/root/anton
EXECUTOR_NUMBER=0
gitlabBranch=test
BUILD_DISPLAY_NAME=#5
gitlabSourceBranch=test
gitlabUserEmail=admin@example.com
JENKINS_VERSION=2.89.4
HUDSON_HOME=/var/jenkins_home
JAVA_DEBIAN_VERSION=8u151-b12-1~deb9u1
JOB_BASE_NAME=anton
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BUILD_ID=5
BUILD_TAG=jenkins-anton-5
gitlabMergeRequestId=1
gitlabActionType=MERGE
JENKINS_URL=http://localhost:8080/
LANG=C.UTF-8
JOB_URL=http://localhost:8080/job/anton/
gitlabSourceRepoName=anton
gitlabSourceNamespace=root
BUILD_NUMBER=5
JENKINS_NODE_COOKIE=63f85221-303e-4906-aca5-59985eb83c63
RUN_DISPLAY_URL=http://localhost:8080/job/anton/5/display/redirect
JENKINS_SLAVE_AGENT_PORT=50000
HUDSON_SERVER_COOKIE=e3dff077c89c3538
JOB_DISPLAY_URL=http://localhost:8080/job/anton/display/redirect
JOB_NAME=anton
COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
PWD=/var/jenkins_home/workspace/anton
JAVA_HOME=/docker-java-home
gitlabUserName=Administrator
```

Limitations:
* Does not work when commenting on the MR, because that GitLab webhook does not include merge request labels.

### CODE REVIEW

**Comment by anton-johansson** [comment]
Hmm, anyone know why the build fails? Tests seem to pass, but it also shows a `Sending interrupt signal to process` before shutting down the process, failing the build.

**Comment by yiftahw** [comment]
I'd be happy to see this feature being merged, I can work to align this if no-one is working on it... @anton-johansson @krisstern @gounthar

**Comment by krisstern** [comment]
Hi @yiftahw it looks like this issue is too old to continue work on it. If you don't mind please start a new PR to start afresh. I could even make this issue a Hacktoberfest one if it can be completed before end of October. Your contribution is very much welcome!

**Comment by yiftahw** [comment]
> Hi @yiftahw it looks like this issue is too old to continue work on it. If you don't mind please start a new PR to start afresh. I could even make this issue a Hacktoberfest one if it can be completed before end of October. Your contribution is very much welcome!

I'll definitely try 😄

**Pull request closed without merging**
