### PR TITLE
Fix gitlabCommitStatus step

### PR DESCRIPTION
**Pull request by stchar**
it should support forms:
    - gitlabCommitStatus()
    - gitlabCommitStatus("buildName") equal to gitlabCommitStatus(name: "buildName")
    - gitlabCommitStatus(Map fields)

### CODE REVIEW

**Comment by omehegan** [comment]
Let me know when this is ready for testing and I will try it locally.

**Comment by omehegan** [comment]
@stchar any progress on this? FWIW I can confirm these tests fail locally as well.

**Comment by omehegan** [comment]
@stchar ping?

**Comment by stchar** [comment]
@omehegan, 
almost done, however I cannot find out why `GitLabConnectionConfigTest` is broken

**Comment by omehegan** [comment]
@stchar thanks a lot, let me test this and then I will merge it!

**Comment by omehegan** [comment]
Released in 1.5.11.

**Comment by dtronche** [comment]
I still have an error message when there is no name :
```
WorkflowScript: 6: Missing required parameter: "name" @ line 6, column 17.
      gitlabCommitStatus {
```
I'm using version 1.5.11 of the plugin and version 2.153 of Jenkins

**Comment by omehegan** [comment]
@dtronche I can't reproduce your issue. I'm using 1.5.11, and I have this test Pipeline code:

```
properties([gitLabConnection('gitlab')])

stage('Build') {
    node {
	gitlabCommitStatus {
	    // The result of steps within this block is what will be sent to GitLab
	    sh "echo 'Building something'"
	}
    }
}

stage('Test') {
  node {
    sh "echo 'Testing something'"
   }
}
```

Works fine and I get this in the job log:

```
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/eline-multibranch_newbranch-PTEAUTWFX4E2P7C5IVGM6PLBHHBECOCHRUHRS3CDPJWB2GWEKPWA
[Pipeline] {
[Pipeline] gitlabCommitStatus
[Pipeline] {
[Pipeline] sh
[eline-multibranch_newbranch-PTEAUTWFX4E2P7C5IVGM6PLBHHBECOCHRUHRS3CDPJWB2GWEKPWA] Running shell script
+ echo Building something
Building something
[Pipeline] }
[Pipeline] // gitlabCommitStatus
[Pipeline] }
```

Can you ensure that you are using 1.5.11 and that you see that in the Installed tab of the Jenkins plugin manager?

**Comment by dtronche** [comment]
Thank you for you answer. 
Here is the stack trace I have, it will probably be more helpful
```
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 6: Missing required parameter: "name" @ line 6, column 17.
                   gitlabCommitStatus {
                   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:131)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:125)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:560)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:521)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:330)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```
The pipeline I'm using:
```
pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                gitlabCommitStatus {
                  script { 
                      sh "echo 'Building something'" 
                     }
                  }
                }
            }
        }
    }
```
Below is a snapshot of my plugins version. So I think this is correct.
image

I'm using a docker image of jenkins but that shouldn't matter, should it ?

**Pull request merged**
