### PR TITLE
Introduces a global webhook url

### PR DESCRIPTION
**Pull request by adjika**
# Configurable Global Webhook URL

## About the WIP status

This PR is WIP to hopefully get some feedback on whether or not there's interest in this PR since I'd likely have to put some additional effort into getting it to an acceptable state.
I'll outline issues and what probably needs to be done prior to removing WIP status at the bottom.

## Description

The objective is to enable Jenkins Admins to define one or several URLs which can be used as GitLab Webhook URLs. Any "GitLab Connection" as configured in the admin panel can have at most one such URL.

## Sample use cases

- Having a global URL instead of job specific ones only synergizes well with "Group Webhooks" (EE feature); a single URL can be defined per GitLab group and upon e.g. a push event those jobs which are configured for the triggering gitlab connection, repository, and branch are triggered.
- Automatically generated jobs don't need to have their specific webhook URLs added to GitLab; At the moment we've got somewhere around 200 jobs generated by the terrific JobDSL plugin, all of which can make use of a single webhook URL which is defined exactly once per GitLab group (EE) or project (CE) instead of once per job.

## Example configuration

grafik
Configure a global webhook bound to a gitlab connection in the jenkins admin panel.

grafik
Set the desired gitlab connection in our job configuration.

grafik
Add the webhook url to a gitlab project/group. The webhook url ends with /project/$configuredGlobalWebhook

From this point on whenever a selected event occurs in the gitlab repo (or group) it will POST to the provided URL, at which point the gitlab-plugin checks whether there's a gitlab connection configured for said URL. It then checks whether any jobs are configured for said gitlab connections, event type, the triggering repository, and possibly the branch. All eligible jobs are then triggered.

## TODO

- Update documentation
- Fix broken formatting / code conventions
- Note events (comments) need to be fixed, currently they only work for job specific webhooks, not global ones
- Probably needs some refactoring, the code is anything but pretty. I also think I introduced a quick&dirty hack with executeNoResponse() because I just needed it to work at the time.
- Adjust logging: noisy log messages have been introduced for printf style debugging.
- Add tests?

## Caveats

- It's not exactly well optimized.  It may not perform up to expected standards, but so far we haven't had any issues with ~500 configured and active jobs, >=250 of which use this feature.

### CODE REVIEW

**Comment by omehegan** [comment]
This is a pretty interesting feature, thanks for working on it! I'm not opposed to it in in principle; people have asked for this type of thing before. Here are the concerns I would want to have addressed before we merge this:

* The diff is already pretty large, and I see you have some concerns about code cleanliness, etc. I want us to maintain the best standard of quality we can for code in the plugin, so please polish this as much as you are able. Use your judgment as to what's best.
* Make sure there are adequate tests. I want to make sure that this change doesn't break existing functionality, and likewise that we don't inadvertently break this feature later.
* Revise documentation to make it clear that there are two different ways to set up job triggers. People sometimes find the configuration process confusing as it is; I don't want to make it more so when we add this feature.

I am planning to do two releases next week; one will release as many of the open PRs as possible, and the other will be moving the plugin to use the GitLab v4 API. The API change will be a breaking change for anyone still using GitLab 8.x, so if that includes you this might be a problem. I suspect your PR won't be ready to merge before then. So just a heads up on that.

**Comment by adjika** [comment]
Thanks for your feedback, I'm working on it!
So far I've fixed most of the cosmetic stuff with regards to the the project's coding style - although I've mostly ignored the different ordering of the imports for now - and implemented the missing global trigger for note events. Some adjustments have to be made mostly wrt logging, documentation needs to be revised and tests need to be written. I'm still not perfectly happy with the code quality of the whole thing, but if you absolutely wanted to include the feature in the presumably last non-bugfix v3 release of the plugin I'd be willing to consider it "good enough" assuming I've completed the other tasks by then.

v4 won't be an issue, we're running 9.x EE and I've got a local branch of this feature which is rebased onto the v4 PR and successfully ran it in production - I had nothing worth sharing though, otherwise I would have commented on the v4 PR.

**Comment by omehegan** [comment]
@adjika I don't mind waiting and putting this PR in the 2.0 release of the plugin, which will be API v4 only. Right now you are the only user of this feature, so if you are using GitLab 9 already then waiting for it to be merged won't be an issue for you :) Just keep working on it and let us know when you think it is ready for review.

@mreichel and @colourmeamused might want to take a look in case they have any guidance about your design and such, that's an area I'm not really suited to comment on.

**Comment by omehegan** [comment]
@adjika I saw your posts on the IRC channel about testing (I'm in GMT-7 timezone so it looks like we do not overlap much). I just pushed some fixes to the docker-compose file which should help make it work better. And I also improved the documentation on how to use that; it's now in the src/docker/ directory. Even if you have never used Docker, I think there is now enough information there for you to get started. That will launch a working Jenkins and GitLab; you would just need to install the plugin and configure a user, repo, webhooks, etc. on the GitLab side.

Failing that, if your network will allow it, yes you could just launch a local copy of Jenkins with the plugin and set up hooks etc.

**Comment by adjika** [comment]
@omehegan Sorry about the late reply, unfortunately I unexpectedly ended up without access to a computer / my github credentials. When I was talking about about "firing up local copy" I was referring to the test harness, I probably didn't express myself well enough.

I've refactored / cleaned up a lot of code, added documentation and included some tests, I have also manually tested push, note and MR events and the gitlab integration post build steps. As a result the PR got a lot smaller and cleaner.

Please feel free to ask any questions or comment on anything you'd like to see changed.
At its current state I feel like the PR is mergeable, so I'm going to remove the WIP status.

**Comment by adjika** [comment]
rebased and squashed commits, no functional changes other than adjusting a few signatures introduced with #614 as required by this PR

**Comment by omehegan** [comment]
@adjika if you want to keep working on this, can you fix the failing tests and merge conflict? Then we can review.

**Comment by adjika** [comment]
@omehegan i just rebased the branch onto master but i'm not seeing any failing tests, could you elaborate which tests are failing for you? 
or did i miss the implied "..if any"? :)

**Comment by omehegan** [comment]
@adjika looks good now! @mreichel or @Argelbargel can you review?

**Comment by adjika** [comment]
@Argelbargel any updates?

**Comment by omehegan** [comment]
@Argelbargel or @mreichel would you be willing to review this?

**Review by mreichel — COMMENTED** [review]
It looks good to me, but I cannot test it without Gitlab EE. Can someone do that?

**Comment by adjika** [comment]
@mreichel you don't necessarily need GitLab EE to test it since group webhooks just pretend to be project level webhooks in their payload, so you can just add a global webhook to a gitlab (CE) project's  webhooks. what you can do to try it out is e.g.:

1. configure a global webhook URL in jenkins for a gitlab connection
2. add said URL as a webhook in a gitlab project, preferrably remove any other configured webhooks for the project to ensure proper testing
3. configure a jenkins job for the repository, choose the gitlab connection you just added a global webhook to, enable "push" trigger
4. push some commits to the repository
5. observe it triggering the jenkins job configured for the repository but no others

I'd be happy to assist if you have any questions, need help testing or if something needs clarification. Feel free to send me an email, you can find my address is in the commit details.

**Comment by adjika** [comment]
@omehegan Is there anything I can do to get the PR merged since @mreichel has signed off on the code and just couldn't try it out herself?

**Comment by omehegan** [comment]
@adjika I'm sorry I haven't had more time to spend on this. Given that it is a fairly big change, what I wanted to do was perform some manual testing of it myself just to make sure no issues jump out at me. I just don't want to break any existing functionality in the plugin, because right now we are in the delicate position of having a rather large number of users but our maintainers (me included) have limited time to spend on the plugin. I have been more focused on bugs than new features recently.

I wish there was a way I could reach out to other users of the plugin who might be interested in this feature, and ask them to test it as well. That would help give us more confidence before we release it.

I will try to spend some time on this soon. I appreciate that you've put significant work into the PR!

**Comment by omehegan** [comment]
@adjika I keep coming back to this PR, getting intimidated at the thought of testing it, and backing away :)  Just wondering what your status is with it: are you still using GitLab, etc.? Do you still want to see this get merged? I should hopefully soon have a license for GitLab EE that I can use to help test features that are specific to that.

**Comment by adjika** [comment]
@omehegan I understand.
We're still using the functionality of this PR in our GitLab EE <-> Jenkins environment and would very much like to see it merged for several reasons: It would save us the effort of maintaining our own fork of the plugin and we'd like to contribute this change so others can hopefully benefit from having the functionality available to them.
This feature saved and saves us a lot of time and headaches and we hope others with a similar infrastructure can make good use of it as well.
As an aside: I'd also like to see it merged for personal reasons: it's the first public PR I opened from this account on github so there'd be pride in the accomplishment :)

If you ping me once you're about to be ready I'll try to find the time to have a look at the accepted MRs of the past few weeks/months and to rebase the branch to make sure everything is working as intended.

**Comment by omehegan** [comment]
@adjika I'm glad you're still engaged and wanting to get this merged! I should soon have an EE license that will allow me to test things like this with more confidence, and I am getting better at using the included Docker environment for that as well. Since the PR has already been reviewed, I think you should rebase it, then I should do some smoke testing, and then we should release it. What's important to me is that if I release a change which breaks things for users, I need to know that someone else will be able to fix it, because I usually can't. Given you're still keen to get this merged after all this time, it sounds like I don't have to worry about that :)

**Comment by adjika** [comment]
@omehegan I understand.
We're still using the functionality of this PR in our GitLab EE <-> Jenkins environment and would very much like to see it merged for several reasons: It would save us the effort of maintaining our own fork of the plugin and we'd like to contribute this change so others can hopefully benefit from having the functionality available to them.
This feature saved and saves us a lot of time and headaches and we hope others with a similar infrastructure can make good use of it as well.
As an aside: I'd also like to see it merged for personal reasons: it's the first public PR I opened from this account on github so there'd be pride in the accomplishment :)

If you ping me once you're about to be ready I'll try to find the time to have a look at the accepted MRs of the past few weeks/months and to rebase the branch to make sure everything is working as intended.

**Comment by omehegan** [comment]
@adjika looks like you have rebased this so I can test it, is that right?

**Comment by adjika** [comment]
@omehegan Yes, and I just rebased it again to make sure everything's working as expected

**Comment by adjika** [comment]
Rebased the branch because there was a merge conflict.

**Comment by omehegan** [comment]
@adjika I have been trying to test your change today, but I am running into an issue. After configuring a global webook endpoint, and changing one of my GitLab projects to use that endpoint, I get a 404 when I try to hit it. I just double-checked that I am running your patched version of the plugin. Am I missing something? I set the webhook URL to http://jenkins/project/globalhook

screen shot 2018-09-16 at 4 04 54 pm

**Comment by adjika** [comment]
@omehegan I'm sorry, I forgot to reply, I've been kinda busy lately but I'll try to reproduce it soon! Just to clarify, you configured it in jenkins, then went to a GitLab instance and tried the "test webhook" button after configuring it and got a 404 there?

**Comment by ghost** [comment]
If you want to merge this please resolve conflict ;) @adjika

**Comment by TobiX** [comment]
Just rebased to resolve the conflict. Some things moved around for CasC-support and I'm not sure I fixed all places...

FYI: Since we moved basically all our projects to GitLab Branch Source, we don't need this feature anymore (and have only limited capacity to test it) - But if this is considered useful for others, we might be able to find some time to push it forward...

**Comment by ghost** [comment]
Please fix this before merge

**Comment by TobiX** [comment]
Pretty sure that's an infrastructure issue with temporary directories on Windows nodes :pensive:

**Comment by basil** [comment]
I just took over this plugin and am preparing for a new release, and to be honest I am quite nervous about this large (unreleased) change. I have no GitLab installation to test against and I am basically just keeping this plugin on life support. If there is a regression caused by this large change, I am not prepared to deal with it. In addition, I am concerned about potential compatibility problems with the addition of the new `globalWebhookURL` parameter to the `GitLabConnection` constructors, which seems to go against the advice in [Constructor vs. setters in the developer documentation](https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#constructor-vs-setters) (I think this should probably have been a `@DataBoundSetter` instead).

@TobiX How strongly do you feel that this should be shipped in the next release? Strongly enough to rework `GitLabConnection` to use `@DataBoundSetter`, re-test the change, and be around to handle any possible regressions? If so, great! If not, I am leaning toward reverting this PR and shipping the next release without it. If and when you, Maxime Mazet, or anyone else wants to push this PR forward, I am happy to facilitate that, but unfortunately I lack the time to do so myself at present and this large change carries a little too much risk for me to feel comfortable with it.

**Comment by brd** [comment]
@basil I can help test it.. I have been running a snapshot for awhile already due to bugs in the released version.

**Comment by basil** [comment]
@TobiX I have temporarily reverted this PR in order to ship 1.5.22. As I wrote earlier, I am not opposed to this RFE, but I lack the time to clean up the code and deal with regressions at present. I am happy to pass the baton to anyone else who wants to take over.

@brd Thank you for volunteering to test the next release. Incremental build 1.5.22-rc1276.9f26cf564af5 is available for testing. Please test the incremental build and report any regressions from 1.5.20.

The incremental build `.hpi` file can be downloaded from here: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/gitlab-plugin/1.5.22-rc1276.9f26cf564af5/

For instructions on how to install a custom build, see: https://www.jenkins.io/doc/book/managing/plugins/#advanced-installation

**Comment by TobiX** [comment]
@basil As I already wrote some months ago: We have moved away from this plugin fully and use gitlab-branch-source exclusivly. (Your ping reminded me to make sure that it was removed from all Jenkins instances) As you see from the history of this PR, we have been using this feature since ~2017 and it simplified much of the configuration for us. If I would implement this today, I would probably skip the configuration option and just implement a fixed URL instead...

That said, I took a quick look what it would take to use a `@DataBoundSetter`, which doesn't seem too complicated... (Just got sidetracked by the strange method `GitLabPushTrigger.migrateJobs` ...) OTOH, I'm not very motivated to re-open this whole pull request, since I have zero use for it... I might be able to help with testing, though...

**Comment by basil** [comment]
Thanks for the quick reply @TobiX. It's up to you: if you open a new PR to re-add this feature, with `@DataboundSetter` and re-testing, I'd be happy to merge and release it once 1.5.22 is out (i.e., in 1.5.23). If you lack the motivation/time/interest, that's fine, too. That's the beauty of open source. If someone really cares about this, then they can step up and shepherd it to completion.

**Pull request merged**
