### PR TITLE
Swap equals check around to prevent NPE

### PR DESCRIPTION
**Pull request by demaniak**
Swapped equals check on strings around to prevent NPE and let the code handle the missing header condition as intended.

### CODE REVIEW

**Comment by demaniak** [comment]
This should prevent the NPE mentioned in #287 

It will of course not magically make the missing header appear :)

**Comment by coder-hugo** [comment]
I don't like this type of comparing strings. As this changes the meaning of the "if-sentence". The current code says: I want to know if the value of the variable eventHeader is (equals) `Merge Request Hook` or `Push Hook`. Your code says: I want to know if `Merge Request Hook` or `Push Hook` is the value of the variable eventHeader.
Jenkins has already the apache commons-lang as a dependency so we should use the StringUtils for a null-safe and syntactical correct equals check.

**Comment by coder-hugo** [comment]
Can you just squash your commits to a single one then I'll merge this PR back.

**Comment by demaniak** [comment]
@coder-hugo oke-doke, I will try to get to that during today.

**Comment by demaniak** [comment]
huh, @coder-hugo find myself unsure how to safely squash the commits (never done before, and I quickly settle this before going home)

I'm just going to close this PR, and re-submit with single commit.

**Pull request closed without merging**
