### PR TITLE
Refactoring data objects to own package

### PR DESCRIPTION
**Pull request by theobisproject**
- Moved data objects like Branch to own data package
- Using [lombok](https://projectlombok.org/) to generate getter and setter

### CODE REVIEW

**Comment by omehegan** [comment]
@markus-mnm would you mind taking a look at this when you have a chance? It's a big change and well above my expertise to assess whether we should take it on board :)

**Comment by markus-mnm** [comment]
I'll check it out this weekend.

**Comment by markus-mnm** [comment]
I believe moving those pojos out is a good idea.
On the other hand I am against using lombok, especially since it requires an IDE plugin.
I would then rather not use getter/setters at all.

EDIT: removed down-vote since that doesn’t seem to do in github what I thought.

**Comment by theobisproject** [comment]
So should i rebase it against master and throw away the lombok commit?

**Comment by markus-mnm** [comment]
yes, please

**Comment by omehegan** [comment]
@theobisproject apologies for the long silence. Is this good to merge now, minus the lombok stuff?

**Comment by theobisproject** [comment]
Yes, lombok stuff is not contained

**Pull request merged**
